compiler/README.md

`  ` was missing in front of the CLI instructions (level indentation with respect to list.

update README.md so it parses correctly the cli instructions

---

compiler/README.md
compiler/opam

- add the repo addresses for coq-released  and coq-extra-dev
- add dependencies to `coq`, `coq-mathcomp-ssreflect` and `coq-mathcomp-algebra` so they are also installed by `opam install --deps-only jasmin`
**Note:** Jasmin also compiles with `coq.8.7`

Add more dependencies to opam

---

compiler/examples/test_add.mil
compiler/src/typing.ml

Currently the `test_add` example fails.
Constant-propagation only considers assignments that are introduced by the compiler. It ignores the assignments to inline variables that are written by the programmer.
This patch makes source-level assignments to inline variable eligible to constant-propagation.

Tag assignments to inline variables as inline

---

compiler/examples/gimli/.gitignore

do not display generated file by `make`

add gitignore in examples/gimli

---

compiler/default.nix

default.nix is missing a dependency 'yojson' to successfully build the compiler via make in the nix-shell

Add missing dependency to default.nix

---

compiler/src/stackAlloc.ml
proofs/_CoqProject
proofs/compiler/array_init_proof.v
proofs/compiler/byteset.v
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/compiler_util.v
proofs/compiler/linear_proof.v
proofs/compiler/merge_varmaps_proof.v
proofs/compiler/stack_alloc.v
proofs/compiler/stack_alloc_proof.v
proofs/compiler/stack_alloc_proof_2.v
proofs/lang/expr.v
proofs/lang/gen_map.v
proofs/lang/low_memory.v
proofs/lang/memory_example.v
proofs/lang/memory_model.v
proofs/lang/psem.v
proofs/lang/psem_facts.v
proofs/lang/sem_one_varmap_facts.v
proofs/lang/type.v
proofs/lang/utils.v
proofs/lang/var.v
proofs/lang/warray_.v
proofs/lang/word.v

Here it is!
Apart from the main changes (in stack_alloc.v, stack_alloc_proof.v and stack_alloc_proof_2.v), I pushed changes in common files (psem.v, memory_model.v, ...). These changes are probably more important to review than the main ones.
Here are a few questions and points to closely look at:
- there are two files stack_alloc_proof.v and stack_alloc_proof_2.v only because the initial file was becoming too big (cf. paragraph at the top of stack_alloc_proof_2.v). Should we keep two different files or should I merge them?
- I performed a renaming `pointer` -> `ptr` for the sake of uniformity with `Uptr` and `sptr` (introduced in stack_alloc_proof.v because I don't know where to put it). But is it worth the trouble?
- Among the changes I made to memory_model.v, I proved …

Proof of the new stack alloc pass

---

compiler/scripts/compile-and-assemble
compiler/src/ppasm.ml

Currently, Jasmin programs that use global variables cannot be dynamically linked (at least on Linux with GCC and GNU binutils). I don’t understand all the details, but the linker complains: “relocation R_X86_64_PC32 against symbol `g' can not be used when making a shared object”.
Maybe we could allow global data to be tagged as `export` to get the current behavior (name is accessible from other compilation units, but only static linking is possible).

Do not export global variables

---

eclib/JModel.ec
eclib/JWord.ec

Add Easycrypt semantics for the following AVX2 instructions:
- VMOVLPD
- VMOVHPD
- SLLVD
- SRLVD
- PACKSSWB

EC semantics for AVX2 instructions

---

eclib/JModel.ec

Add (and update) Easycrypt semantics for the following AVX2 instructions:
- PACKUSWB
- VPBLEND
- VMOVSLDUP
- VPMULHRSW

Add EC semantics for more AVX2 instructions

---

eclib/JModel.ec
eclib/JWord.ec

Simplify `VPMOVMSKB` semantic in EC

Clean EC semantic for VPMOVMSKB instruction

---

eclib/JModel.ec
eclib/JWord.ec

- Update EC semantics specification for the VPEXTR instruction 
- Add support for `VPEXTRB` (VPEXTR_8) and `VPEXTRD` (VPEXTR_32)

Update EC semantics for VPEXTR instruction

---

eclib/JModel.ec
eclib/JWord.ec

- EC semantics for the `SETcc` instruction
- Update EC semantics for the `VPMOVMSKB`  instruction to support more destination sizes
- EC semantics for the `VINSERTI128` instruction

EC semantics

---

.gitignore
coqword.nix
default.nix
proofs/3rdparty/ssrring.v
proofs/_CoqProject
proofs/compiler/lowering.v
proofs/compiler/lowering_proof.v
proofs/lang/strings.v
proofs/lang/type.v
proofs/lang/utils.v
proofs/lang/var.v
proofs/lang/word.v
proofs/ssrmisc/oseq.v

This updates Jasmin to make it compatible with Coq 8.12 and math-comp 1.11 (and only these versions). It implicitly updates the OCaml dependency to 4.10.
Using math-comp 1.12 is not currently possible due to a bug affecting all released versions of Coq (https://github.com/coq/coq/issues/13581). Said bug shall be fixed in future version 8.14.0 of Coq (https://github.com/coq/coq/pull/13624). Note that the patch that fixes the Coq bug can be applied as-is to Coq 8.12.2.

Use Coq 8.12 and Mathcomp 1.11

---

compiler/safety/success/array-direct.jazz
compiler/src/safety/safetyInterpreter.ml

Currently, the safety checker crashes when verifying alignment constraints of “direct” (not scaled) array accesses.

Safety checker: fix alignment constraints for direct array accesses

---

compiler/src/pretyping.ml
compiler/tests/fail/typing/write_constant_pointer_direct_array.jazz
compiler/tests/fail/typing/write_constant_pointer_direct_var.jazz
compiler/tests/fail/typing/write_constant_pointer_subproc_array.jazz
compiler/tests/fail/typing/write_constant_pointer_subproc_var.jazz

Pointers that aren't returned are inferred to be constant; any attempt at
writing to such a pointer should be considered an error.
Closes #81.

Reject programs that attempt to write a constant pointer during typing

---

compiler/Makefile
compiler/config/tests.config
compiler/scripts/parse-print-parse
compiler/src/glob_options.ml
compiler/src/liveness.ml
compiler/src/main_compiler.ml
compiler/src/printLinear.ml
compiler/src/printer.ml
compiler/src/printer.mli
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/regalloc.ml

This PR tries to ensure that Jasmin programs printed by the compiler are indeed written in Jasmin syntax. In particular, the output of `-pcstexp` is always syntactically valid (and usually well-typed); this is now checked by the test-suite.
This is a breaking change (in particular printed programs are now displayed on `stdout` instead of `stderr`).
Feature requested by Tiago (@tfaoliveira).

Pretty-print intermediate programs in correct Jasmin syntax

---

compiler/src/regalloc.ml

Avoid merging vector and non-vector variables during register-allocation

---

eclib/JModel.ec

BSWAP is used in libjade, but doesn't have easycrypt semantics defined. This adds some semantics.

add easycrypt semantics for BSWAP

---

.gitlab-ci.yml

The address that is currently in use seems to confuse gitlab’s UI.

ci: use a dummy email address in the jasmin-compiler repository

---

proofs/lang/utils.v

We recently merged https://github.com/coq/coq/pull/15754 which removed support for `_` in `ident`, after a period of deprecation. Since Jasmin was recently added to the CI, the CI run for that PR missed the fact that the `Let` notation defined here is using ident. This PR changes `ident` to the correct `name`, which allows for underscores.

fix Let notation

---

opam

Jasmin is compatible with Coq 8.15 & mathcomp 1.14

opam: relax version constraints

---

.github/actions/nix/action.yml
.github/workflows/ci.yml

We migrate all CI steps except pushing to cachix.
The main motivation is a better integration in the development workflow (PRs, etc) since the main Jasmin repository is on GitHub.
Note: before merging, a deploy key should be set up to target the jasmin-compiler repo, and the URL should be updated accordingly.

Migrate CI to Github Actions

---

CHANGELOG.md

I realized we are testing with option `-ptyping`, not `-pcstexp` so I changed the Changelog accordingly.

Minor change in changelog

---

.gitlab-ci.yml
default.nix
scripts/nixpkgs.nix
scripts/opam-setup.sh

This should prevent the cache of the OPAM root to rot, as long as it stays in sync with the pinned nixpkgs.
(The update of nixpkgs is not related.)

CI: refactor opam job

---

compiler/CIL/LICENSE.coq
compiler/CIL/LICENSE.coqword
compiler/CIL/LICENSE.mathcomp
compiler/LICENSE
compiler/MANIFEST
compiler/README.md

The problem is that currently there is no LICENSE file in the compiler tarball. And the situation of CIL is complex, since its contents is extracted from various sources.
This is a light fix, editing a bit the README and adding a few LICENSE files. Maybe we should specify for each file where it comes from, but this is tedious, so let's at least postpone that. I took the easy solution to have all this static. We could imagine adding these files while generating the tarball.
Fix https://github.com/jasmin-lang/jasmin/issues/114

Better licensing for compiler-only distribution

---

Makefile

In PR https://github.com/jasmin-lang/jasmin/pull/111, I broke the `install` rule when `PREFIX` is a relative path. My fix is simply to ask `make` to compute the absolute path first. I don't think it's a beautiful fix, if you have a better idea (including reverting the PR), please do suggestions.

Export absolute PREFIX from toplevel Makefile

---

compiler/src/toEC.ml

We take the straightforward approach that may introduce some noise in the extraction. We could be more clever, but at least this removes 2 `assert false`.

Fix some assert false in toEC.ml

---

compiler/src/pretyping.ml
compiler/tests/fail/typing/only_param.jazz

We catch an exception and in some cases reemit a different one. I think it is better not to catch it in these cases (which means the original exception is displayed to the user).

Pretyping: keep the error when OnlyParam

---

scripts/fix_path_ro.patch
scripts/opam-setup.sh

This script is only meant to be run in contenerized CI jobs, thus there
is no need for an additional layer of sandboxing

opam: disable sandboxing

---

.gitlab-ci.yml
scripts/test-libjade.sh

This makes the `proof/` directory of libjade: extract jasmin programs to EasyCrypt and run EasyCrypt of the generated code.
cc @tfaoliveira

CI/libjade: test extraction to EasyCrypt

---

proofs/compiler/arch_params.v
proofs/compiler/lea.v
proofs/compiler/x86_params.v

Running `make CIL` no longer compiles any `_proof` file!

clean spurious Require

---

compiler/examples/strlen.jazz

I’ve just been told that it is not always necessary to write wrappers in a foreign language to call a function written in Jasmin. Here is an illustration.

Example standalone Jasmin program

---

proofs/lang/values.v

Definition of `subtype` and related lemmas in `proofs/lang/values.v` was ducplicated from `proofs/lang/type.v`.

Removed duplicate definition of subtype

---

.gitlab-ci.yml
compiler/default.nix

When using a recent `nixpkgs` (i.e., strictly posterior to 21.11), building from sources the released version of Jasmin fails with:
> \+ ocamlfind ocamlopt -rectypes -linkpkg -g -package 'batteries, menhirLib, zarith, apron.octMPQ, apron.ppl, apron.boxMPQ, yojson' -I entry jasmin.cmx entry/jasminc.cmx -o entry/jasminc.native
> …/ld: cannot find -lcamlidl: No such file or directory
> collect2: error: ld returned 1 exit status
This PR fixes this issue (well, not for released versions…).

compiler/default.nix: add missing dependency on camlidl

---

compiler/src/glob_options.ml
compiler/src/main_compiler.ml

This makes the `Glob_options` module independent of `Unix`

Reset the default `call_conv` in `main_compiler`

---

compiler/MANIFEST
compiler/_tags
compiler/src/ct_checker_forward.ml
compiler/src/intervalGraphColoring.ml
compiler/src/latex_printer.ml
compiler/src/ppasm.ml
compiler/src/printLinear.ml
compiler/src/printer.ml
compiler/src/prog.ml
compiler/src/regalloc.ml
compiler/src/safety/domains/safetyDisjunctive.ml
compiler/src/ssa.ml
compiler/src/subst.ml
compiler/src/toEC.ml
compiler/src/varalloc.ml
compiler/src/x86_arch_full.ml
proofs/_CoqProject

This PR gets rid of an ugly workaround in `_CoqProject` and enables OCaml warnings 32 and 34: they warn about unused type & value declarations.
This allow to remove (or use) some dead code.
Side-note: warning 32 fires a lot in the `safety/` directory, so I kept it disabled there (to be fixed later).

Minor cleaning

---

CHANGELOG.md
compiler/src/regalloc.ml
compiler/tests/success/bug_175.jazz

Remove renaming assignements irrespective of “writable” annotation

---

CHANGELOG.md
compiler/tests/success/mem2mem.jazz
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v

This is more uniform and avoids cryptic error messages from asm-gen

Enable lowering of various memory-to-memory moves

---

proofs/compiler/tunneling.v
proofs/compiler/tunneling_proof.v
proofs/lang/linear.v
proofs/ssrmisc/seq_extra.v

Motivation: less code & proofs to maintain.

Linear: linstr need not be an eqType

---

proofs/compiler/merge_varmaps_proof.v
proofs/lang/utils.v

Currently, trying to `Require Import Uint63.` fails with:
> Error: Notation "_ >> _" is already defined at level 25 with arguments constr at level 25, constr at next level
while it is now required to be at level 30 with arguments constr at next level, constr at next level.
The first patch fixes this issue.
The second patch removes the single (real) use of `stk_fun_extra` as an `eqType`.

Two trivial fixes

---

proofs/3rdparty/xseq.v
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/unrolling.v
proofs/compiler/unrolling_proof.v
proofs/lang/expr.v

This might be more efficient, and this allows to clean away some tedious `eqType` definitions.

Loop unrolling: change halting condition

---

CHANGELOG.md
compiler/src/conv.ml
compiler/src/conv.mli
compiler/src/evaluator.ml
compiler/src/main_compiler.ml
compiler/src/printer.ml
proofs/arch/asm_gen.v
proofs/arch/asm_gen_proof.v
proofs/compiler/array_init.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/merge_varmaps_proof.v
proofs/compiler/remove_globals.v
proofs/compiler/tunneling.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v
proofs/lang/expr.v
proofs/lang/expr_facts.v
proofs/lang/extraction.v
proofs/lang/psem.v

This seems to be good for performances (of the compiler).
The following table reports compilation times (in seconds) for `.jazz` files in libjade and the corresponding (base-2) speed-up.
Thanks Tiago for the `jtiming` script in libjade!
~~~
path                               before   after    change
────────────────────────────────────────────────────────────
onetimeauth/poly1305/ref             0.08     0.08     0.0
hash/sha3-224/avx2                   0.94     0.93     0.02
hash/sha3-256/avx2                   0.94     0.93     0.02
hash/sha3-384/avx2                   0.94     0.93     0.02
hash/sha3-512/avx2                   0.94     0.93     0.02
stream/chacha/chacha12/avx           5.82     5.65     0.04
stream/chacha/chacha12/avx2          5.74     5.59     0.04 …

Extract instr_info & var_info to standard OCaml int

---

CHANGELOG.md
compiler/src/pretyping.ml
compiler/src/prog.ml
compiler/src/prog.mli

Fixes #199
Currently, the following program makes the Jasmin compiler crash with an assertion failure:
~~~
inline
fn f(reg u64 a) -> reg u64 {
return a;
}
export
fn g(reg u64 x) -> reg u64 {
reg u64 y;
y = 0;
y = f(x) if x > 1;
return y;
}
~~~
This change makes it produce a normal error message (with line numbers & colors).

pretyping: there are no conditional function calls

---

CHANGELOG.md
compiler/tests/success/bug_200.jazz
proofs/compiler/x86_lowering.v

Lowering: add a missing case when assigning a not-equal comparison

---

compiler/jasmin.mlpack.in
compiler/src/glob_options.ml
compiler/src/main_compiler.ml
compiler/src/printStats.ml
compiler/src/printStats.mli

New command-line option “-pstats” shows on stdout in CSV form a few
properties about generated functions: number of instructions, of SLH
primitives, etc.

Print basic stats about compiled programs

---

CHANGELOG.md
compiler/src/pretyping.ml
compiler/src/printer.ml

This prevents source-level intrinsics to be removed by dead-code
elimination.
Fixes #220

Pretyping: use AT_keep for Copn

---

CHANGELOG.md
compiler/src/varalloc.ml
compiler/tests/success/bug_190.jazz

Stack-alloc: fix inference of mutability of ptr arguments

---

compiler/src/insert_copy_and_fix_length.ml

insert-array-copy: do not crash on ill-typed programs

---

compiler/jasmin.mlpack.in
compiler/src/annotations.ml
compiler/src/conv.ml
compiler/src/conv.mli
compiler/src/ct_checker_forward.ml
compiler/src/iInfo.ml
compiler/src/latex_printer.ml
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/syntax.ml

This breaks a circular dependency between extracted and hand-written
OCaml code

OCaml: move “annotations” to their own module

---

compiler/src/varalloc.ml
compiler/tests/success/syscall/align.jazz

According to System V AMD64 ABI Draft 0.99.7, stack frames must be aligend to 16 bytes at function call boundaries.
Fixes #240

stack-alloc: fix stack alignment with syscalls

---

CHANGELOG.md
compiler/src/parser.mly
compiler/tests/success/ifelse.jazz

This patch add syntactic sugar for `else if` constructions. E.g.:
```jazz
if x == 0 {
// (...)
} else if x == 1 {
// (...)
} else {
// (...)
}
```
is parsed as if it were: 
```jazz
if x == 0 {
// (...)
} else {
if x == 1 {
// (...)
} else {
// (...)
}
}
```

Add `else if` construction

---

CHANGELOG.md
compiler/src/glob_options.ml
compiler/src/toEC.ml

Extraction to EasyCrypt may write extra `ArrayN.ec` and `WArrayN.ec` files.
The directory into which these files are written can be changed using the `-oecarray dir` command-line argument.
The default behavior is to write in the current directory (i.e., from which `jasminc` is run).
I would like to turn this off (i.e., do not write extra files unless explicitly asked for), but that would break the LibJade test suite.

[cli] Choose directory for EC extraction of Array support libraries

---

compiler/src/toEC.ml
compiler/tests/success/test_randombytes.jazz

The current method should work, but it is not very elegant. 
Maybe we should discuss more on it.

Extract randombytes

---

CHANGELOG.md
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v

A comment says this should be removed…
Does this need an entry in the CHANGELOG?

x86: remove support for explicit if-then-else in flag combinations

---

compiler/tests/success/vector.jazz
eclib/JModel.ec
proofs/compiler/x86_instr_decl.v
proofs/lang/word.v

This commit adds support for the (signed) (V)PMULDQ instruction under the name #VPMUL.
All support was based on the support for the (unsigned) VPMULUDQ instructions, so I conveniently based all the new code on that code.
Reviewing suggestions:
* check if the semantics in `word.v` are correct;
* check if I did not forget to add anything
---
Cc @vbgl
Fixes #274

Add support for VPMUL instructions

---

proofs/arch/arch_decl.v
proofs/arch/arch_extra.v
proofs/arch/asm_gen_proof.v
proofs/compiler/arm_instr_decl.v
proofs/compiler/x86_extra.v
proofs/compiler/x86_instr_decl.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/psem.v
proofs/lang/sopn.v

This field is generally meaningless. It is heuristically used in lowering on x86 to check whether an immediate value fits within the instruction or should go through an intermediate register.
I believe that the current design is bad and that the cleaning done in this commit is a necessary step towards a better design (that is yet to be discovered).

Remove field id_wsize from instruction descriptors

---

CHANGELOG.md
compiler/src/annotations.ml
compiler/src/checkAnnot.ml
compiler/src/pretyping.ml
compiler/src/printer.ml
compiler/src/stackAlloc.ml
compiler/tests/fail/annotation/calldepth.jazz
compiler/tests/success/calldepth.jazz
proofs/compiler/stack_alloc.v
proofs/lang/expr.v

Proof of concept @bgregoir 
Should a function that calls no other function have 0 or 1 for "max call depth"?

Compute max call depth

---

compiler/src/conv.ml
compiler/src/conv.mli
compiler/src/pp_arm_m4.ml
proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v

This fixes some examples using `movt`.
This also corrects a terminology confusion between alloc and free…

arm: immediate arguments are non-negative

---

CHANGELOG.md
compiler/examples/arm_m4/intrinsic_ror.jazz
compiler/examples/arm_m4/ror.jazz
compiler/src/latex_printer.ml
compiler/src/lexer.mll
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/printer.ml
compiler/src/safety/safetyAbsExpr.ml
compiler/src/safety/safetyInterpreter.ml
compiler/src/syntax.ml
compiler/src/toEC.ml
compiler/tests/success/test_rotations.jazz
eclib/JWord.ec
proofs/compiler/arm_decl.v
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/expr.v
proofs/lang/sem_op_typed.v
proofs/lang/word.v

Extend lexing and parsing with `<<r` and `>>r`.
Extend latex and EasyCrypt printing.
Define operators in `eclib/JWord.ec`.
Implement lowering for x86 and ARM-M4.

Add ROL and ROR operators

---

CHANGELOG.md

I bugged when looking at the changelog: where is the "2022.04.0" version? It turns out the old name "22.0" was still in use in the changelog.

Fix version name in changelog

---

proofs/arch/asm_gen_proof.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/psem.v

The dependency was artificial. This requires to add some `(spp:=mk_spp)`, but it seems we cannot avoid those.

Make estate not depend on SemPexprParams

---

CHANGELOG.md
compiler/src/pretyping.ml
compiler/src/printCommon.mli
compiler/src/utils.ml
compiler/src/utils.mli
compiler/tests/success/vmovsxdup.jazz
eclib/JModel.ec
proofs/compiler/x86_instr_decl.v

x86: VMOVSxDUP instructions accept a single size suffix

---

CHANGELOG.md
compiler/safety/success/copy.jazz
compiler/src/safety/safetyInterpreter.ml

safety-checker: support #copy

---

CHANGELOG.md
compiler/src/regalloc.ml
compiler/tests/fail/register_allocation/bug_310.jazz

Based on #311 
Fixes #310, #186, #12.

regalloc: fail when some reg bool variables remain unallocated

---

.gitlab-ci.yml

Fix breakage due to #318.
CI in progress: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/737915893

CI: use a recent docker image

---

compiler/syscall/jasmin_syscall.c
compiler/syscall/jasmin_syscall.h

I tested with the distribution package of libjade, and it appears to work.

randombytes syscall : fixing types + ptr copy for returning

---

CHANGELOG.md
compiler/safety/success/bug_314.jazz
compiler/src/safety/domains/safetyNum.ml
compiler/src/safety/safetyVar.ml
compiler/src/safety/safetyVar.mli

checksafety: reset A/M-var conversion table

---

CHANGELOG.md
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/syntax.ml
compiler/tests/success/divmod.jazz

There seems to be no justification to the current limitation.

DIV and MOD can be used in compound assignments

---

eclib/JArray.ec

A lemma had a useless hypothesis. This PR removes it. May break some EC proofs using Jasmin arrays.

Removed useless hypothesis in Array.set_neqiE

---

CHANGELOG.md
compiler/safety/success/int_shift.jazz
compiler/src/safety/safetyAbsExpr.ml

Fixes #319
(The first commit is unrelated, but it does not deserves a PR on its own.)
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/738147944

checksafety: better handling of integer shift operators

---

compiler/src/pp_arm_m4.ml
compiler/src/ppasm.ml
compiler/src/printLinear.ml
proofs/arch/arch_decl.v
proofs/arch/arch_sem.v
proofs/arch/asm_gen.v
proofs/arch/asm_gen_proof.v
proofs/arch/label.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/tunneling.v
proofs/compiler/tunneling_proof.v
proofs/lang/linear.v
proofs/lang/linear_sem.v

External labels correspond to return addresses, or more generally to targets of computed jumps.
External labels may be encoded as a pointer and then stored in registers or in memory.
As the (unspecified) encoding of labels only depends of the set of external labels, adding fresh internal labels is guaranteed to preserve the encoding.

Distinguish internal from external labels

---

compiler/src/alias.ml
compiler/tests/pending/cmoveptr.jazz

This is a trivial fix. Proper handling of uncertainty about `ptr` targets seems more daunting.

Turn a reachable “assert false” into a proper error

---

.gitlab-ci.yml
compiler/examples/arm_m4/set_up_stack.jazz
compiler/src/arch_full.ml
compiler/src/arch_full.mli
compiler/src/arm_arch_full.ml
compiler/src/regalloc.ml
compiler/src/x86_arch_full.ml
proofs/compiler/arm_lowering.v
proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v
proofs/lang/expr.v
proofs/lang/linear_sem.v
proofs/lang/psem.v
proofs/lang/utils.v
proofs/lang/var.v
proofs/lang/word.v

The architecture parameter that aligns the stack pointer for export functions is now an optional piece of code, instead of an instruction.
Since in some architectures (ARMv7 and RISC-V for instance) we need an extra register whether we store the stack pointer in a register or in the stack, the function that chooses where to store the stack pointer now excludes certain variables (the extra register in these cases).
The solution implemented in ARM is not optimal: if the value is in [0, 4095], it can be done in one instruction, if it fits in 16 bits in two, and otherwise we use what's implemented now. But what is implemented now always works and I'll add this optimization shortly.

Arm stack alignment

---

compiler/examples/arm_m4/stack.jazz
compiler/src/pp_arm_m4.ml

There is no CALL instruction on ARM…
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/758228456

ARM: fix pretty-printing of JAL & CALL asm instructions

---

scripts/coqword.nix

Let’s use a recent version of mathcomp!
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/761741478

default.nix: mathcomp 1.12 → 1.15

---

CHANGELOG.md
compiler/tests/success/bug_340.jazz
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v

The first round, before expansion of register arrays, does not apply to cells of register arrays. The second round fixes this limitation.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/765177635

Compiler: perform two rounds of range splitting

---

proofs/compiler/x86_decl.v
proofs/compiler/x86_params.v

There was no way to interact with this flag.

Remove DF flag from x86

---

default.nix

I left this after linting the new files by mistake, I'm really sorry.

Remove ocamlformat from default.nix

---

CHANGELOG.md
compiler/safety/fail/array_init.jazz
compiler/safety/success/parr_init.jazz
compiler/src/safety/safetyAbsExpr.ml
compiler/src/safety/safetyAbsExpr.mli
compiler/src/safety/safetyInterpreter.ml

Currently, the safety checker crashes when it encounters an explicit `ArrayInit` “instruction”.
Note that some of the added code is not tested as I don’t know how to exercise it…

Checksafety: soundly handle ArrayInit

---

compiler/src/main_compiler.ml
proofs/compiler/arch_params.v
proofs/compiler/arch_params_proof.v
proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v

It is already part of the compiler params, and shared with other passes.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/783160558

Remove is_regx from lowering-params

---

CHANGELOG.md
compiler/safety/fail/bounded_while.jazz
compiler/safety/success/bounded_while.jazz
compiler/safety/success/trusted-termination.jazz
compiler/src/safety/safetyInterpreter.ml
compiler/src/safety/safetyPreanalysis.ml
compiler/tests/success/stack_array.jazz

While loops with a `#bounded` annotation are optimistically unrolled during safety analysis until the loop condition can be refuted.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/790348734

Safety checker: on-demand unrolling of while loops

---

compiler/src/regalloc.ml
compiler/tests/fail/arm-m4/bug_201.jazz

The classification of registers between general-purpose “word”-sized registers and “vector” registers depends on the architecture.
Fixes #201

Register allocation: register banks depend on arch

---

eclib/JWord.ec

JModel has a borderline (in term of timeout) `smt` call that do not pass anymore when moving to Why3 1.6.
This PR simplifies this `smt` call.

Fix borderline smt calls in JModel

---

CHANGELOG.md
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/safety/safetyInterpreter.ml
compiler/src/safety/safetyPreanalysis.ml

Variables that are involved in the guards of bounded loops need not be put in the relational domain.

checksafety: heuristic for bounded loops

---

compiler/entry/jazz2tex.ml
compiler/jasmin.mlpack.in
compiler/src/arch_full.ml
compiler/src/arch_full.mli
compiler/src/arm_arch_full.ml
compiler/src/coreArchFactory.ml
compiler/src/coreArchFactory.mli
compiler/src/main_compiler.ml
compiler/src/x86_arch_full.ml
compiler/src/x86_safety.ml
compiler/src/x86_safety.mli

IIRC, this function has been put there only for convenience, without a good reason.

Move the safety analyzer out of the Arch modules

---

.gitlab-ci.yml
proofs/_CoqProject
proofs/compiler/jasmin_compiler.v
proofs/lang/extraction.v
scripts/nixpkgs.nix

Fixes #377.
With this change, no CI job (apart from itself) depend on the `coq-proof` one, which checks all Coq proofs. Therefore, even when proofs are (transiently) broken, other jobs (testing libjade, building the tarball, etc) can go on.

CI: split the Coq job

---

default.nix
scripts/easycrypt.nix

Fix after https://github.com/EasyCrypt/easycrypt/pull/352

[CI] EasyCrypt: use why3 1.6.0

---

CHANGELOG.md
compiler/tests/success/x86-64/vector.jazz
proofs/compiler/x86_instr_decl.v
proofs/lang/word.v

Attempt to fix a bug in the handling of #VPEXTR_8 and #VPEXTR_16, which are currently miscompiled into "vpextrq".

fix a bug on the handling of #VPEXTR_8 and #VPEXTR_16

---

CHANGELOG.md
compiler/tests/success/x86-64/vpclmulqdq.jazz
eclib/JModel.ec
proofs/compiler/x86_instr_decl.v

This PR adds support for the carry-less multiplication instructions (PCLMULQDQ and VPCLMULQDQ).

add support for PCLMULQDQ instructions

---

CHANGELOG.md
compiler/src/glob_options.ml
compiler/src/safety/safetyInterpreter.ml

When the `-nocheckalignment` flag is given on the command-line, alignement issues no longer count as safety violations.
For expert users only, use at your own risk.
cc @cryptojedi

Safety: add -nocheckalignment command-line flag

---

default.nix

This is useful for devs working on the Jasmin OCaml code using an LSP-based IDE.

Add ocaml-lsp to dev tools

---

CHANGELOG.md
compiler/examples/x86-64/hw.jazz
compiler/tests/success/x86-64/opsizes.jazz
compiler/tests/success/x86-64/test_rotations.jazz
compiler/tests/success/x86-64/test_shift.jazz
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/word.v
scripts/test-libjade.sh

This is meant as a first step before the semantics of shifts changes.
With this change, the compiler is able to correctly compile current and future jasmin programs. This will allow to update existing jasmin programs before breaking changes are introduced to the compiler.

x86 lowering: handle shifts with explicit masking

---

CHANGELOG.md
compiler/src/glob_options.ml
compiler/src/main_compiler.ml
compiler/src/slicing.ml
compiler/src/slicing.mli

Slicing removes from a program functions and global variables that are not reachable from the selected functions.
This feature has been requested in the context of safety checking: it allows to analyze a single entry-point within a larger program.
Nonetheless it may be used for different purposes and in particular it makes the already available `-checkCTon` and `-ec` arguments somehow redundant.
cc @tfaoliveira

jasminc: Add a `-slice f` command line argument

---

compiler/Makefile
compiler/config/tests.config
compiler/scripts/parse-print-parse
compiler/src/tt_arm_m4.ml
compiler/tests/success/arm-m4/intrinsic_adc.jazz
compiler/tests/success/arm-m4/intrinsic_add.jazz
compiler/tests/success/arm-m4/intrinsic_and.jazz
compiler/tests/success/arm-m4/intrinsic_bic.jazz
compiler/tests/success/arm-m4/intrinsic_eor.jazz
compiler/tests/success/arm-m4/intrinsic_mvn.jazz
compiler/tests/success/arm-m4/intrinsic_orr.jazz
compiler/tests/success/arm-m4/intrinsic_rsb.jazz
compiler/tests/success/arm-m4/intrinsic_sub.jazz
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v

This PR implements a few things; I can split it if required:
- support for intrisics with shifted arguments using operator syntax, e.g., `#ADD(x, y >> 2)`
- use this syntax in the tests and drop support for the old syntax `#ADD(x, y, #LSR(2))`
- test the pretty-printer for ARM in the test-suite and on CI
Dropping support for the old syntax enables me to implement extraction to EasyCrypt in a simple way.

ARM: intrinsics with shifts

---

proofs/_CoqProject
proofs/arch/arch_utils.v
proofs/compiler/arm_decl.v
proofs/compiler/x86_decl.v

Move common patterns to `arch_utils`, remove some unused lemmas and old comments.

Cleanup architecture declarations

---

CHANGELOG.md
compiler/tests/success/x86-64/bt.jazz
proofs/compiler/x86_instr_decl.v

- There is no 8-bit variant for this instruction
- The generated assembly is now well-formed

x86: fixes for instruction BT

---

compiler/src/pretyping.ml
compiler/src/regalloc.ml
proofs/arch/arch_extra.v
proofs/lang/sopn.v

From outside Coq we don't need to distinguish `reg` and `flag` implicit arguments.

Change sopn.implicit_arg to var

---

CHANGELOG.md
compiler/src/compile.ml
compiler/tests/fail/stack_allocation/x86-64/bad_alignment.jazz
compiler/tests/fail/stack_allocation/x86-64/merge_global_param.jazz
compiler/tests/fail/stack_allocation/x86-64/merge_globals.jazz
compiler/tests/fail/stack_allocation/x86-64/non_constant_index.jazz
compiler/tests/fail/stack_allocation/x86-64/pointer_to_stack2.jazz
compiler/tests/fail/stack_allocation/x86-64/range_overflow.jazz
compiler/tests/fail/stack_allocation/x86-64/slice_same.jazz
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v

Local functions that are not reachable from any “export” functions are
removed from the program after inlining.
The compiler notoriously exhibits weird behaviors when local functions
are never called.

Prune unused local functions

---

proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/stack_alloc.v
proofs/compiler/stack_alloc_proof.v
proofs/compiler/stack_alloc_proof_2.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v

Ensure (and enforce) that there are no assignment left when reaching the linearization pass.
- Lowering must handle all existing assignments
- Passes that come after should not introduce new assignments.
Does this need a changelog entry?

Handle assignments before linearization

---

compiler/scripts/runtest

1. Remove unused imports.
2. `parse.error` does not exist.
3. `_parse_timeout` is never used.
4. `ok   = [x for x in group if     x.success]` is never used.
5. `sp.kill()` does not exist.
6. `def gather(obj, scenario):` never uses `scenario`.

Fix typos, remove dead code in runtest

---

proofs/arch/arch_decl.v
proofs/arch/arch_extra.v
proofs/arch/arch_utils.v
proofs/arch/asm_gen.v
proofs/arch/asm_gen_proof.v
proofs/compiler/arm_decl.v
proofs/compiler/arm_extra.v
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_instr_decl_lemmas.v
proofs/compiler/arm_params_proof.v
proofs/compiler/compiler.v
proofs/compiler/stack_alloc.v
proofs/compiler/x86_decl.v
proofs/compiler/x86_extra.v
proofs/compiler/x86_instr_decl.v
proofs/lang/expr.v
proofs/lang/strings.v
proofs/lang/syscall.v
proofs/lang/type.v
proofs/lang/utils.v
proofs/lang/warray_.v
proofs/lang/wsize.v

General cleanup (prefer `Scheme Equality`) and move some more definitions to `arch_utils` for when I come back to OTBN. Should I use `t_eq_axiom` in other files? (or remove it?)

Cleanup and move architecture utils

---

proofs/compiler/array_copy_proof.v
proofs/compiler/array_init_proof.v
proofs/compiler/makeReferenceArguments_proof.v
proofs/compiler/stack_alloc_proof.v
proofs/compiler/stack_alloc_proof_2.v
proofs/lang/psem.v
proofs/lang/type.v
proofs/lang/values.v
proofs/lang/warray_.v

WArray.cast fail if the size are not equal. subtype and WArray.uincl and value_uincl require equal size for array.

subtype and value_uincl require equal size for array

---

CHANGELOG.md
proofs/lang/word.v

Reading the doc carefully, it becomes clear that SRC2 is not read from YMM2.

x86: fix semantics of VPERMD, VPMADDWD, & VPMADDUBSW

---

eclib/JWord.ec

Current model is wrong, and there are no known use of this flag.

eclib: do not attempt to model the parity flag

---

CHANGELOG.md
eclib/JWord.ec
proofs/compiler/x86_instr_decl.v

The manual reads: “For the SHR instruction, the OF flag is set to the most-significant bit of the *original* operand.”
I know that RCL and RCR do not compute the `CF` flag correctly, but I still do not understand the details of the issue…

x86: fix semantics of SHR, RCL, and RCR

---

compiler/src/parseio.ml

Its documentation reads:
> This function is extremely costly and is provided essentially for
> debugging purposes or for reusing legacy libraries which can't be
> adapted. As a general rule, if you can avoid using this function, don't
> use it.
Its implementation has a known bug that leads to exhaustion of available file descriptors and filesystem space (see:
https://github.com/ocaml-batteries-team/batteries-included/blob/134a8873ebdef76117978b61062c8682e3cdac35/src/batIO.ml#L710).

Do not use BatIO.to_input_channel

---

compiler/src/compile.ml
compiler/src/conv.ml
compiler/src/conv.mli
compiler/src/coreIdent.ml
compiler/src/coreIdent.mli
compiler/src/pretyping.ml
compiler/src/regalloc.ml
compiler/src/stackAlloc.ml
proofs/compiler/allocation.v
proofs/compiler/allocation_proof.v
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/makeReferenceArguments.v
proofs/compiler/makeReferenceArguments_proof.v
proofs/lang/extraction.v
proofs/lang/ident.v
proofs/lang/wsize.v

First commit is unrelated.
Instead of relying on the fact that the `fresh_id` oracle returned fresh variable names, it is now called with different arguments:
- different call sites are distinguished by their `instr_info`;
- different arguments / return values are distinguished by the value of a (local) counter that is incremented on each call to said oracle.

Improve fresh name generations in make-reference-arguments

---

.gitlab-ci.yml

With this change, the [jasmin-compiler](https://gitlab.com/jasmin-lang/jasmin-compiler/) git repository tracks the OCaml source code as well as the EasyCrypt support library.
Next step would be to include said EasyCrypt library in the release artifacts.

CI: push eclib to the jasmin-compiler repository

---

CHANGELOG.md
compiler/safetylib/domains/safetyProduct.ml
compiler/safetylib/safetyPreanalysis.ml
compiler/safetylib/safetyPreanalysis.mli
compiler/src/compile.ml
compiler/src/liveness.ml
compiler/src/liveness.mli
compiler/src/printer.ml
compiler/src/printer.mli
compiler/src/regalloc.ml
compiler/src/removeUnusedResults.ml
compiler/src/removeUnusedResults.mli
compiler/src/ssa.ml
compiler/src/ssa.mli
compiler/src/stackAlloc.ml
compiler/src/varalloc.ml
compiler/tests/success/x86-64/bug_455.jazz

Liveness: improve for register allocation

---

compiler/safety/success/flags.jazz
compiler/safetylib/safetyAbsExpr.ml

Current behavior is to crash (`assert false`).

Safety checker: minimal support for flag combinations

---

compiler/src/compile.ml
compiler/src/regalloc.ml
compiler/src/regalloc.mli
compiler/src/stackAlloc.ml
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/linearization_proof.v
proofs/compiler/merge_varmaps.v
proofs/compiler/merge_varmaps_proof.v
proofs/lang/sem_one_varmap.v
proofs/lang/sem_one_varmap_facts.v

These registers where use to compute the return address before we used the CALL instruction.

Reg. allocation: remove “extra free registers”

---

compiler/tests/success/arm-m4/mulu.jazz
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v

This is much more complex than expected as the order of the destinations is different for the jasmin operator and the ARM instruction.

ARM/lowering: High-level syntax for 32→64-bit multiplication

---

CHANGELOG.md
compiler/tests/success/arm-m4/multiply-and.jazz
eclib/JModel_m4.ec
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v

Lowering introduce these instructions when compiling expressions of the form: x ± y * z.

ARM: add instructions MLA and MLS

---

CHANGELOG.md
compiler/tests/success/arm-m4/intrinsic_smlal.jazz
compiler/tests/success/arm-m4/intrinsic_smmul.jazz
compiler/tests/success/arm-m4/intrinsic_smmulr.jazz
compiler/tests/success/arm-m4/intrinsic_smull.jazz
compiler/tests/success/arm-m4/intrinsic_umlal.jazz
eclib/JModel_m4.ec
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_lowering_proof.v
proofs/lang/word.v

Added UMLAL, SMULL, SMLAL, SMMUL & SMMULR instructions.

Arm instructions for long multiplication

---

CHANGELOG.md
compiler/src/compile.mli
compiler/src/pretyping.ml
compiler/src/pretyping.mli
compiler/tests/fail/typing/x86-64/bug_69.jazz
proofs/arch/arch_decl.v
proofs/arch/arch_extra.v
proofs/compiler/arm_instr_decl.v
proofs/compiler/x86_extra.v
proofs/compiler/x86_instr_decl.v
proofs/lang/sopn.v

- Pre-typing now rejects some silly programs (#69)
- There is now a single type `prim_constructors`

Improvements to casted primitive operators

---

compiler/src/dune
compiler/src/parser.mly

The inspection API is useful for the language server to be able to derive a concrete syntax tree (for e.g. semantic highlighting, refactorings, etc) as part of the parsing phase.
It will also help generating nicer error messages without manually crafting messages. But that part is waiting on a license clarification on the Menhir side (some relevant code we'd need to reuse is currently GPL 2).
Note: the changes in `parser.mly` are required because Menhir doesn't seem to support module definitions when it generates the `.mli` files for the interpreter API.

Enable inspection API in parser

---

CHANGELOG.md
proofs/compiler/x86_instr_decl.v

This pull request is to fix #515. The patch has been validated against single-instruction fuzz-test with sizes 16, 32 and 64 variants.
Apologies for the large diff as my editor removes white spaces on save automatically. 
Actual diff is between lines 503 to 512.

FIX LZCNT semantics to handle the size parameter

---

proofs/compiler/x86_instr_decl.v

Currently all the instructions are printed in lower case except the MULX. 
This change will make the MULX instructions to be printed in lowercase.
Current:
`MULXq   %rdx, %r15, %r14 `
Fix:
`mulxq   %rdx, %r15, %r14`

Fix instruction printing of MULX

---

compiler/MANIFEST

Before this change, the dune files from the tests directories got included in the tarball altough the source and data of the tests are not.

Select which dune files are included in the tarball

---

CHANGELOG.md
eclib/JModel_m4.ec
proofs/compiler/arm_instr_decl.v

Bug found by random testing.
cc @Slukoo

ARM: rewrite semantics of SMMULR instruction

---

compiler/src/pretyping.ml
compiler/src/pretyping.mli

There are no good reasons to hide this function, right?

Pretyping.tt_prim: export & simplify

---

compiler/tests/success/subroutines/x86-64/nolea.jazz
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v

Before:
~~~
movq    %rsp, %rsi
leaq    (%rsp), %rsp
andq    $-8, %rsp
~~~
After:
~~~
movq    %rsp, %rsi
andq    $-8, %rsp
~~~

x86-linearization: do not allocate empty stack frame

---

proofs/compiler/arm_instr_decl.v
proofs/compiler/x86_lowering_proof.v
proofs/compiler/x86_params_proof.v
proofs/lang/word.v

This changes the specification for two word operations: `wdaddu` and `wumul`. Now we use `Z.shiftr` instead of `Z.quot`. I feel that the former is a more natural way of modelling these operations. I can roll back the changes for these two if not.
This removes the need for `wmulhuE`.

Use high_bits instead of wrepr and Z.shiftr or Z.quot

---

CHANGELOG.md
compiler/src/sct_checker_forward.ml
compiler/tests/success/common/bug_540.jazz
compiler/tests/success/common/inline-global.jazz
proofs/compiler/constant_prop.v
proofs/compiler/constant_prop_proof.v
proofs/compiler/slh_lowering.v
proofs/compiler/slh_lowering_proof.v

This makes constant-propagation stronger: when global data (word or array) is accessed in an inline computation (assignment to inline variables, including inline arguments to (inline) functions), its value is computed at compile-time.
Caveat: global variables that are never accessed excepted in such “inline” situations are still present in the assembly code.
Fixes #540.

Constant-propagation: propagate global values in “inline” context

---

compiler/examples/gimli/proofs/.gitignore
compiler/examples/gimli/proofs/Makefile
compiler/examples/gimli/proofs/gimli_ct.ec
compiler/examples/gimli/proofs/gimliv.ec
compiler/examples/gimli/x86-64/gimliv.jinc
eclib/JWord.ec

I thought that the lemma about `zeroextu128` could be useful in other contexts, so I put it in the `JWord` library.

Gimli: proofs for the AVX implementation

---

CHANGELOG.md
compiler/tests/success/common/bug_499.jazz
proofs/compiler/array_copy.v
proofs/compiler/array_copy_proof.v

Fixes #499.
~Currently a draft as it depends of #549 to avoid conflicts. (This did not work as expected…)~

Array-copy: no ArrayInit when LHS is a ptr

---

compiler/src/compile.ml
proofs/compiler/compiler.v
proofs/lang/var.v

Remove one more field from compiler params. And some cleaning too. `is_reg_array` still exists on the OCaml side (and is used), so it's not 100% clear to me that this PR is worth it, but every field removed from compiler params is a small victory.

Implement is_reg_array in Coq

---

proofs/compiler/x86_instr_decl.v

Division by zero throws arithmetic error `Error ErrArith`

`div` & `idiv` should throw ErrArith not type_error

---

compiler/safetylib/safetyPreanalysis.ml

Note that the order of the elements in `if_conds` does not matter: this list represents a set.

safety checker: avoid not tail-rec list concatenation

---

proofs/arch/arch_decl.v
proofs/arch/arch_extra.v
proofs/compiler/stack_alloc_proof.v
proofs/lang/sem_params.v
proofs/lang/sopn.v
proofs/lang/utils.v

This is to prepare for future versions of Coq

Coq: remove uses of :> to declare instances

---

proofs/compiler/arch_params_proof.v
proofs/compiler/arm_decl.v
proofs/compiler/arm_params_proof.v
proofs/compiler/compiler_proof.v
proofs/compiler/propagate_inline_proof.v
proofs/compiler/x86_decl.v
proofs/compiler/x86_params_proof.v
proofs/lang/flag_combination.v
proofs/lang/sem_op_typed.v

There are two parts to this PR, I can split it if it's worth it.
The propagate inline pass relies on the fact that interpreting a flag combination as an expression and evaluating it is the same as interpreting the values as a booleans (`sem_pexpr` composed with `fc_sem enot eand eor eeq` is `fc_sem negb andb orb eqb`). This uses an architecture parameter but is true regardless of what it does.
I removed the `CFC_O` constructor because `combine_flags_core` is how we represent conditions (`==`, `!=`, `<=`, `<`, etc.) and there is no condition for overflow (i.e. it's inaccessible from the source). The overflow flag is needed to compute some conditions, but we don't need the condition by itself. You can see this in the definition of `cf_tbl`: `CFC_O` is not the image of any `combine_flags`.

Remove propagate inline parameters and remove CBC_O

---

compiler/src/arm_arch_full.ml
proofs/compiler/arm_decl.v
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v
proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v
proofs/lang/expr.v
proofs/lang/expr_facts.v
proofs/lang/utils.v

While working on lowering for OTBN and some other lowering changes related to combine flags, I felt like we could simplify the code by adding an equivalent to `Let` but for options.
I think it's clearer because we indent less, avoid intermediate definitions (to later match against `Some`), and use `subst` instead of `case` in proofs (so we don't need to care about dependencies in hypotheses).
For the definition of `let%opt` I tried using `obind` instead of matching, but it blocked reduction in many places and I felt using `match` made things simpler. I couldn't get `Option.obindP` to work, that's why I defined one outside the module. We don't seem to use `Option.obindP`, but I would like to know how to use it instead of the one I defined.
Also, we defined `VarI _ dummy_var_info`  in …

Add monadic let for options

---

proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v
proofs/compiler/propagate_inline_proof.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/expr.v
proofs/lang/sem_op_typed.v
proofs/lang/word.v

The logic to replace conditions with flags was duplicated: `fc_of_cfc` (in arch decl) and `lower_cond` (in each lowering pass). I changed this so that lowering maps conditions to flag combinations (`==` to `CF_EQ`) that then get lowered to flag combinations by Propagate Inline. A good thing now is that we prove that `fc_of_cfc` maps high-level conditions to flags correctly (previously we didn't need to because the semantics of `combine_flags` is architecture specific).

Use combine_flags in lowering

---

CHANGELOG.md
compiler/tests/success/arm-m4/sub.jazz
compiler/tests/success/arm-m4/sub_using_RSB.jazz
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v

Should I add something in the change log?

use RSB for x = (y << n) - z;

---

proofs/compiler/arm_params_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/x86_params_proof.v
proofs/lang/linear.v
proofs/lang/utils.v
proofs/lang/var.v

I had to do this to patch the linearization proof after I added new instruction to the linear language and changed linear states. I think the changes make sense in any case.

Name fields of linearization parameters and split up some lemmas

---

CHANGELOG.md
proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v

Now `$ ./jasminc -arch arm-m4 tests/success/arm-m4/memcmp.jazz -pasm` gives
```
memcmp:
push	{lr}
SUB 	r12, sp, #8
```
instead of
```
memcmp:
push	{lr}
MOV 	r12, #8
MOVT	r12, #0
SUB 	r12, sp, r12
```
Closes #379.

Optimize arm_cmd_large_arith_imm

---

proofs/lang/psem_defs.v

The compiler does not need to depend on expr_facts.

Remove unneeded dependency on expr_facts

---

compiler/scripts/runtest

This helps differentiate different test scenarios for the same file.

Add full command to runtest messages

---

compiler/tests/fail/x86-64/shift.jazz
proofs/compiler/linearization.v

In response to the last few questions on Zulip. I know that Lowering is not necessarily the culprit here, so the error message might be misleading (although I believe that the passes after Lowering no longer introduce assignments). But I think the worst case scenario is what currently happens: get confused, have to ask on Zulip.

Change Cassgn error message in linearization

---

CHANGELOG.md
compiler/tests/success/arm-m4/intrinsic_bfc.jazz
compiler/tests/success/arm-m4/intrinsic_bfi.jazz
eclib/JModel_m4.ec
proofs/arch/arch_utils.v
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_instr_decl_lemmas.v
proofs/lang/utils.v
proofs/lang/word.v

Please double check the EasyCrypt part, I'm really not familiar with it.

ARM: Add BFI and BFC

---

compiler/src/sct_checker_forward.ml
compiler/tests/sct-checker/fail/modmsf-trace.jazz
compiler/tests/sct-checker/reject.expected
compiler/tests/sct-checker/sct_errors.expected

Before promoting the expected output, can anyone help me print the trace properly? I played around with pretty-printing boxes to no success. Should each item be printed inside a `@[ ... @]`?

SCT checker: Keep a trace in modmsf

---

CHANGELOG.md
compiler/src/glob_options.ml
compiler/src/pretyping.ml
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/toEC.ml
compiler/src/utils.ml
compiler/src/utils.mli
compiler/tests/success/common/test_warn_var.jazz

clearer resolution of variables + add warning

---

CHANGELOG.md
compiler/tests/success/arm-m4/intrinsic_clz.jazz
compiler/tests/success/arm-m4/intrinsic_smla_hw.jazz
compiler/tests/success/arm-m4/intrinsic_smul_hw.jazz
compiler/tests/success/arm-m4/intrinsic_smulw_hw.jazz
eclib/JModel_m4.ec
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_instr_decl_lemmas.v

ARM: Add signed multiply halfwords instructions

---

compiler/tests/sct-checker/sct_errors.expected
compiler/tests/sct-checker/sct_errors.ml

Nobody checked those line numbers, and they make it hard to update the test case.

SCT tests: do not show line numbers

---

compiler/src/sct_checker_forward.ml
compiler/tests/sct-checker/sct_errors.expected

This example
```
inline
fn f() -> #msf reg u64 {
reg u64 msf;
msf = #init_msf();
return msf;
}
export
fn protect_leak(#transient reg u64 x) -> #public reg u64 {
reg u64 msf;
msf = f();
x = #protect(x, msf);
x = x;
return x;
}
```
doesn't work with `-checkSCTafter inline`

SCT checker: accept compiler introduced assignments to MSF

---

compiler/src/regalloc.ml

Before this patch, an argument can be replaced by a local variable during renaming, meaning that its name changes (confusing for the user) and its kind can change (a `reg mut ptr` can become `reg constr ptr`, cf. `tests/success/x86-64/bug_190.jazz`).

Renaming: ensure that arguments are preserved

---

.gitlab-ci.yml
scripts/nixpkgs.nix

This gives access to latest versions of Coq (8.18) & math-comp (2.1)

CI: update nixpkgs & nix

---

proofs/arch/asm_gen_proof.v
proofs/compiler/array_init_proof.v
proofs/compiler/linearization_proof.v
proofs/compiler/makeReferenceArguments_proof.v
proofs/lang/psem.v
proofs/lang/psem_of_sem_proof.v
proofs/lang/varmap.v

Te PR https://github.com/coq/coq/pull/18374 moved the "_ =1 _" notation of ssreflect from function_scope to type_scope. This requires some disembiguation wit the "_ =1 _" of Jasmin in vm_scope.

Fix after https://github.com/coq/coq/pull/18374

---

CHANGELOG.md
compiler/safetylib/domains/safetyNum.ml

The standard `@` has known issues

Safety checker: avoid list concatenation

---

compiler/tests/sct-checker/accept.expected
compiler/tests/sct-checker/error_messages.jazz
compiler/tests/sct-checker/success/local-stack-array.jazz
opam
proofs/_CoqProject
proofs/compiler/array_init_proof.v
proofs/compiler/linearization_proof.v
proofs/lang/word.v

- Get rid of notations deprecated in math-comp 1.17
- Use local lemmas instead of Let that trigger warnings with Coq 8.18
- Ensure function arguments are used in the tests for the SCT checker.

Address a few kinds of warnings

---

default.nix
scripts/easycrypt.nix

There is no need neither for Why3IDE nor for the EasyCrypt OCaml libraries

nix: less dependencies

---

proofs/arch/asm_gen_proof.v
proofs/arch/label.v
proofs/compiler/arm_params_common_proof.v
proofs/compiler/arm_params_proof.v
proofs/compiler/arm_stack_zeroization_proof.v
proofs/compiler/compiler_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/stack_zeroization_proof.v
proofs/compiler/tunneling_proof.v
proofs/compiler/x86_params_proof.v
proofs/compiler/x86_stack_zeroization_proof.v
proofs/lang/linear_facts.v
proofs/lang/linear_sem.v
proofs/lang/low_memory.v
proofs/lang/memory_model.v
proofs/lang/psem.v
proofs/lang/utils.v

Using explicit records for `lstate`s in lemmas makes changing that datatype very involved. I made some cosmetic changes to `eval_instr` in `linear_sem` to use `Let` instead of if-then-else, let me know if you think it's a bad idea.
Sorry for the string of boring refactoring PRs, hopefully I'm done.

Avoid explicitly using lstate records

---

proofs/compiler/arm_params.v
proofs/compiler/arm_params_common.v
proofs/compiler/arm_params_common_proof.v
proofs/compiler/arm_params_proof.v
proofs/compiler/arm_stack_zeroization.v
proofs/compiler/arm_stack_zeroization_proof.v
proofs/lang/expr.v
proofs/lang/fexpr.v

I parameterized the common operations defined in arm params so that we can use them for `Copn` and `Lopn`. I don't think we can easily abstract the proofs, but if you let me know how I would like to.

Move arm utils to a module

---

CHANGELOG.md
compiler/scripts/check-arm-m4
compiler/scripts/check-x86-64
compiler/src/debugInfo.ml
compiler/src/debugInfo.mli
compiler/src/glob_options.ml
compiler/src/pp_arm_m4.ml
compiler/src/pp_arm_m4.mli
compiler/src/ppasm.ml
proofs/arch/arch_decl.v
proofs/arch/arch_sem.v
proofs/arch/asm_gen.v
proofs/arch/asm_gen_proof.v

Demo: when compiling the program below (`jasminc -o crash.s crash.jazz && cc -o crash crash.s`) and running it within `gdb`, here is the resulting output:
~~~
Program received signal SIGSEGV, Segmentation fault.
main () at crash.jazz:6
6         r = (u8)[end];
~~~
Here are the full contents of `crash.jazz`:
~~~
export
fn main(reg u64 argc argv) -> reg u8 {
reg u64 end;
reg u8 r;
end = [argv + 8 * argc];
r = (u8)[end];
return r;
}
~~~
and the assembly listing produced by `jasminc`:
~~~
.att_syntax
.text
.p2align        5
.globl  _main
.globl  main
_main:
main:
.file 1 "crash.jazz"
.loc 1 5 2
movq    (%rsi,%rdi,8), %rax
.loc 1 6 2
movb    (%rax), %al
ret
~~~

Compiler: emit DWARF2 line number information

---

proofs/arch/arch_decl.v
proofs/arch/arch_sem.v
proofs/arch/asm_gen_proof.v
proofs/compiler/arm.v
proofs/compiler/arm_params_proof.v
proofs/compiler/x86.v
proofs/compiler/x86_params_proof.v

Adapt x86 and arm proofs to handle the additional argument. Renames specific arm Definition of eval_cond to arm_eval_cond. Use generic eval_assemble_cond definition for arm_eval_assemble_cond.

 eval_cond also take registers as argument.

---

CHANGELOG.md
compiler/CCT/fail/div_secret.jazz
compiler/CCT/fail/mod_secret.jazz
compiler/CCT/success/div.jazz
compiler/src/arch_full.ml
compiler/src/arch_full.mli
compiler/src/arm_arch_full.ml
compiler/src/ct_checker_forward.ml
compiler/src/ct_checker_forward.mli
compiler/src/main_compiler.ml
compiler/src/sct_checker_forward.ml
compiler/src/sct_checker_forward.mli
compiler/src/x86_arch_full.ml
compiler/tests/sct-checker/accept.ml
compiler/tests/sct-checker/reject.ml
compiler/tests/sct-checker/sct_errors.ml

The constant time checker ensures that if the division or modulo operator can only be used on public value

CT checker requires public input for div and mod

---

compiler/jasmin.opam

This fixes the `opam-compiler` CI job.

opam: ez-conf-lib is broken

---

CHANGELOG.md
compiler/src/pretyping.ml
compiler/tests/success/common/bug_729.jazz

Just emit a warning if said call is not annotated as inline
Fixes #729

Pretyping: accept all calls to export functions

---

proofs/compiler/x86_instr_decl.v

We were protected from this being a problem by pretyping. `grep` says we don't have this pattern anywhere else...

Fix let instead of Let in x86_instr_decl

---

proofs/compiler/arm_stack_zeroization_proof.v
proofs/compiler/linearization_proof.v
proofs/compiler/stack_alloc_proof.v
proofs/compiler/x86_stack_zeroization_proof.v
proofs/lang/low_memory.v
proofs/lang/memory_model.v

The removed lemma has too strong hypotheses (that may not hold when memory accesses are not aligned…).

writeP_neq: remove redundant lemma

---

CHANGELOG.md
compiler/src/fInfo.ml
compiler/src/slicing.ml

Slicing: turn export functions into inline ones unless there are explicitly asked to be kept

---

eclib/easycrypt.project
eclib/tests.config

Specifying the provers version numbers allows EasyCrypt to select the provers that best match the ones that were in use during the development.
Note that project files & specifying version numbers is not available in the last release of EasyCrypt. Hence, one test of the CI is expected to fail (eclib against EasyCrypt release). I don't know what is the Jasmin policy for that.

eclib: use a project file + specify provers versions

---

.gitignore
default.nix

This change makes it possible to call nix-build from the repository root. It also allows to pin specific versions of the jasmin compiler in a nix shell. For example like this:
```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
jasmin-src = pkgs.fetchFromGitHub {
owner  = "Rixxc";
repo   = "jasmin";
rev    = "c523a9e20bae85e028c6cb9b0b55bfc3f8f3734b";
hash   = "sha256-6cDmfj55mYwTQE0Fka7s3/EuBts9hj+65xgWQ7OTez8=";
};
jasmin = pkgs.callPackage "${jasmin-src}/default.nix" { inherit pkgs; };
in
pkgs.mkShell {
nativeBuildInputs = [
jasmin
];
}

feat: allow nix-build from repository root

---

CHANGELOG.md
compiler/src/iInfo.ml
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v
proofs/compiler/arm_stack_zeroization_proof.v
proofs/compiler/array_init.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/expr.v
proofs/lang/extraction.v

Fixes #718.
Partly taken from #736.
cc @J08nY

Attach more precise meta-data to variables introduced at compile-time

---

compiler/Makefile

Currently the `*.cmi`, `*.cmt`, and `*.cmti` files are not build so that Merlin and ocaml-lsp-server can be used in the project.

Add @check alias to dune call in Makefile

---

compiler/Makefile
compiler/config/tests.config
compiler/scripts/check-risc-v
compiler/src/CLI_errors.ml
compiler/src/coreArchFactory.ml
compiler/src/coreArchFactory.mli
compiler/src/glob_options.ml
compiler/src/main_compiler.ml
compiler/src/pp_riscv.ml
compiler/src/pp_riscv.mli
compiler/src/riscv_arch_full.ml
compiler/src/sct_checker_forward.ml
compiler/src/toEC.ml
compiler/tests/fail/risc-v/basics.jazz
compiler/tests/success/risc-v/basics.jazz
proofs/_CoqProject
proofs/compiler/jasmin_compiler.v
proofs/compiler/riscv_decl.v
proofs/compiler/riscv_extra.v
proofs/compiler/riscv_instr_decl.v
proofs/compiler/riscv_lowering.v
proofs/compiler/riscv_params.v
proofs/compiler/riscv_params_common.v
proofs/compiler/riscv_params_core.v
proofs/lang/extraction.v

Provides slightly more than the minimum bits to compile a void function.
Many success/common  tests pass.
success/risc-v/basics.jazz pass.

Riscv compiler skeleton

---

proofs/compiler/compiler_proof.v

Prior to this change, type-checking these lemma applications takes a
long time.

Help the type-checker

---

compiler/default.nix
compiler/jasmin.opam
compiler/src/annotations.ml
compiler/src/dune
compiler/src/sct_checker_forward.ml
compiler/src/securityAnnotations.ml
compiler/src/securityAnnotations.mli
compiler/tests/sct-checker/dune
compiler/tests/sct-checker/sct_annot.ml
compiler/tests/sct-checker/success/arrays.jazz
compiler/tests/sct-checker/success/basic.jazz
compiler/tests/sct-checker/success/corruption.jazz
compiler/tests/sct-checker/success/for_loop.jazz
compiler/tests/sct-checker/success/paper.jazz
compiler/tests/success/slh/x86-64/function_calls.jazz
compiler/tests/success/slh/x86-64/function_kills_msf_2.jazz
default.nix
opam

The value of this annotation is a security signature for the function. Said signature gives the security type  of each argument and returned value.
A security level is a pair (first component for normal, correctly speculated executions, second component for mis-speculated executions) made of:
- “public”
- “secret”
- an arbitrary identifier
There are a few notational shortcuts:
- “transient” denotes the pair (public, secret)
- a lone component x denotes the pair (x, x)
A type for non-ptr variables is just a level. A type for a ptr variable is made of two levels: one for the value (i.e., the array), the other one for the reference (aka the pointer) which may become transient when unspilled from memory.

SCT-checker: accept “sct” annotation for functions

---

scripts/nixpkgs.nix

This brings OCaml 4.14.2 & alt-ergo 2.5.3

CI: update nixpkgs

---

CHANGELOG.md
compiler/src/regalloc.ml
compiler/tests/success/common/liveness.jazz

When using `-pliveness`, the information about variables from caller functions that are live across the whole function now lists each call site separately and shows relevant location information.

Regalloc: clearer printing of live variables at call sites

---

CHANGELOG.md
compiler/CCT/success/sct.jazz
compiler/src/ct_checker_forward.ml
compiler/src/sct_checker_forward.ml
compiler/tests/sct-checker/error_messages.jazz
compiler/tests/sct-checker/fail/basic.jazz
compiler/tests/sct-checker/reject.expected
compiler/tests/sct-checker/sct_errors.expected
compiler/tests/sct-checker/sct_errors.ml
compiler/tests/sct-checker/success/annot.jazz

Security annotations for the speculative-ct checker are translated (weakened) when handled by the (non-speculative) CT checker.

CT checker: accept S-CT annotations

---

compiler/src/ct_checker_forward.ml
compiler/src/glob_options.ml
compiler/src/main_compiler.ml
compiler/src/sct_checker_forward.ml

Minor CLI and CT checker cleanups

---

CHANGELOG.md
compiler/entry/jazzct.ml
compiler/src/CLI_errors.ml
compiler/src/glob_options.ml
compiler/src/main_compiler.ml

Let’s make some room for a better interface.

Remove deprecated legacy interface to the CT checker

---

CHANGELOG.md
compiler/src/pp_arm_m4.ml
compiler/tests/success/arm-m4/load_immediate.jazz
proofs/arch/asm_gen_proof.v
proofs/compiler/arm_decl.v
proofs/compiler/arm_extra.v
proofs/compiler/arm_instr_decl_lemmas.v
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v
proofs/compiler/arm_params.v
proofs/compiler/arm_params_common.v
proofs/compiler/arm_params_common_proof.v
proofs/compiler/arm_params_core.v
proofs/compiler/arm_params_core_proof.v
proofs/compiler/arm_params_proof.v
proofs/compiler/arm_stack_zeroization.v
proofs/compiler/arm_stack_zeroization_proof.v
proofs/compiler/x86_params_proof.v
proofs/lang/expr.v
proofs/lang/expr_facts.v
proofs/lang/fexpr.v
proofs/lang/psem.v
proofs/lang/pseudo_operator.v
proofs/lang/sopn.v

The idea is to move everything in `ARMFopn` to extra ops that the compiler uses transparently and get solved in asm_gen.
This PR does this for loading an immediate in a register. We decided to lower assignments `x = imm` to this operator, even if it can generate two instructions.

Add smart load immediate operator for ARM

---

proofs/lang/expr_facts.v
proofs/lang/psem.v

Trying to better understand the `pexpr_ind` induction principle, I got the impression that it is generally less convenient to use than the mutual induction principle `pexprs_ind_pair`.

pexpr_ind: simpler proofs

---

.gitlab-ci.yml
opam
proofs/compiler/arm_facts.v
proofs/lang/memory_model.v
proofs/lang/word.v
scripts/mathcomp-word.nix

This will allow to easily change the implementation of `lsr`.
The `opam` CI job has been failing a lot recently (by needing too much memory) and does not know about development versions of `mathcomp-word`: I’ve thus disabled it.

Rework a few proofs about word.lsr

---

CHANGELOG.md
compiler/scripts/check-arm-m4
compiler/src/pretyping.ml
compiler/src/tt_arm_m4.ml
compiler/src/tt_arm_m4.mli
proofs/compiler/arm_instr_decl.v
proofs/lang/sopn.v

Reject ARM intrinsics with an S when they do not support it

---

CHANGELOG.md
compiler/src/ppasm.ml
compiler/tests/success/x86-64/vector.jazz

This is meant to improve compatibility with GNU binutils 2.41
Fixes #803.

ASM: print 8-bit immediates unsigned

---

CHANGELOG.md
compiler/safety/success/swap.jazz
compiler/safetylib/safetyInterpreter.ml
compiler/src/pretyping.ml
compiler/tests/fail/x86-64/swap128.jazz
compiler/tests/fail/x86-64/swap_bool.jazz
compiler/tests/fail/x86-64/swap_int.jazz

This prevents a few unpleasant crashes.

Fixes regarding the swap pseudo-operator

---

CHANGELOG.md
compiler/safety/success/slh.jazz
compiler/safetylib/safetyInterpreter.ml

Safety-checker: support for SLH primitives

---

scripts/nixpkgs.nix

It notably includes:
- GNU binutils 2.41
- Coq 8.19
- mathcomp 2.2.0
- OCaml 5.1.1

CI: update nixpkgs (to channel 24.05)

---

compiler/safety/fail/array-export.jazz
compiler/safety/success/array-export.jazz
compiler/safetylib/domains/safetyPointsTo.ml
compiler/safetylib/safetyAbsExpr.ml

Do not crash; assume arrays are initialized

Checksafety: minimal support of arrays in export functions

---

CHANGELOG.md
compiler/tests/success/x86-64/shift.jazz
eclib/JWord.ec
proofs/compiler/x86_instr_decl.v

Shifts & rotations that:
1. do not affect flags
2. may have different source & destination

Add x86 instructions RORX, SARX, SHRX, SHLX

---

compiler/src/regalloc.ml

The optimization that conflicts between variables allocated to disjoint banks can be ignored is now applied only to variables of “reg” kind.
Fixes #827.

Register allocation: minor improvement

---

CHANGELOG.md
compiler/tests/success/x86-64/aes_instr.jazz
eclib/JModel_x86.ec
proofs/compiler/x86_instr_decl.v

The AES-NI AVX instructions are extended to 256-bit operands.
Fixes #630.

x86: add VAES instructions

---

.gitlab-ci.yml
default.nix

This job compiles the Coq sources of the Jasmin compiler with the current master branch of Coq.

CI: add a coq-master job

---

compiler/jasmin.opam
opam

I submitted https://github.com/ocaml/opam-repository/pull/26051 to add the latest Jasmin release to opam, and it revealed that we are not compatible with batteries < 3.5. I think we have been incompatible for a long time, so I don't know why opam's CI that is really good at testing lower bounds did not catch this problem for previous releases.

Raise lower bound on batteries in opam files

---

CHANGELOG.md
compiler/tests/fail/lower_spill/needs_to_be_spilled_not_spilled.jazz
compiler/tests/fail/lower_spill/needs_to_be_spilled_overwritten.jazz
compiler/tests/success/common/dead_spill.jazz
proofs/compiler/lower_spill.v
proofs/compiler/lower_spill_proof.v

- The lower-spill transformation only skips functions in which no `#spill` or `#unspill` operation appear (fixes #719)
- This transformation introduces assignment without a flag: this allows the following passes (in particular dead-code-elimination) to remove them when appropriate.

Improvements to lower-spill

---

CHANGELOG.md
compiler/tests/success/subarrays/x86-64/copy_partial.jazz
compiler/tests/success/subarrays/x86-64/spill_partial.jazz
compiler/tests/success/subarrays/x86-64/swap_partial.jazz
proofs/compiler/stack_alloc.v
proofs/compiler/stack_alloc_proof.v

Before this patch, an assignment `a = b`, where `a` and `b` are two arrays, was allowed only if `b` was fully valid, and `a` was marked as fully valid too. After this patch, `b` does not need to be fully valid, and `a` is marked as having the same validity as `b`.
The motivation was to enable more freedom in the spilling of reg ptr. In particular, I needed the following pattern to be accepted.
```
reg ptr u64[N*K] r;
reg ptr u64[N] p;
for i = 0 to K {
p = r[N*i:N];
() = #spill (r); // f is using a lot of registers, so we have to spill as much as we can
p = f (p);
() = #unspill (r); // r is not fully valid due to the call, so this was rejected before
r[N*i:N] = p;
}
```

stack alloc: relax the checker

---

AUTHORS
CHANGELOG.md
compiler/CCT/fail/doit/x86_64/rol.jazz
compiler/CCT/fail/doit/x86_64/xchg.jazz
compiler/CCT/success/doit/by_stack.jazz
compiler/Makefile
compiler/config/tests.config
compiler/entry/jasmin_ct.ml
compiler/src/arch_full.ml
compiler/src/arch_full.mli
compiler/src/arm_arch_full.ml
compiler/src/x86_arch_full.ml

This is derived from PR #736. It adds to the architecture descriptions data about which instructions have “Data Operand Independent Timing” (DOIT). The CT checkers can use this data to verify that sensitive (secret) information is only operated through such instructions.

Add support for DOIT

---

.gitlab-ci.yml
default.nix
scripts/coq-elpi.nix
scripts/nixpkgs.nix

- Update `nixpkgs` to support latest `coq-elpi`
- Fix `coq-elpi` derivation
- Allow the `coq-master` CI job to fail and disable it on `release-*` branches.

CI: fixes for job coq-master

---

proofs/compiler/byteset.v

Adapt to https://github.com/coq/coq/pull/18449
This compiles with Coq master and should be backward compatible.
There should be a CI here testing at least that no PR here breaks compilation with Coq master, so that we can add Jasmin back into Coq CI.

Adapt to coq/coq#18449

---

compiler/Makefile
compiler/src/typing.ml

Could we do some Makefile magic to have the `CHECKCATS` variable be "the strings `[test-<ident> `" of tests.config?

Add SCT to CHECKCATS, fix error message typo

---

.editorconfig

`.editorconfig` is a file to tell most text editors how to format files (indentation, ...)
https://editorconfig.org/

Add .editorconfig file for OCaml files formatting

---

.gitlab-ci.yml
scripts/test-libjade.sh

Libjade is undergoing heavy refactoring. This is a hacky fix to keep things working meanwhile.

CI: fix libjade jobs

---

CHANGELOG.md
compiler/src/sct_checker_forward.ml
compiler/tests/sct-checker/accept.expected
compiler/tests/sct-checker/fail/bug_887.jazz
compiler/tests/sct-checker/reject.expected
compiler/tests/sct-checker/success/bug_887.jazz

SCT: fix checking of while loops

---

.editorconfig

According to the [spec](https://spec.editorconfig.org/index.html#supported-pairs), `utf8` is not a supported value for the `charset` key.
Fixes #891.

editorconfig: fix spelling of utf-8 charset

---

AUTHORS
CHANGELOG.md
compiler/src/latex_printer.ml
compiler/src/lexer.mll
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/syntax.ml

jasmin2tex program always convert integer from source file to base 10. In certain cases, it makes readability of the program harder. For example : 
```jazz
tab[i] = 0xab;
```
is converted to :
```tex
\jasminindent{2}tab[i] = 172;\\
```
We implement a new Syntax node `pbinteger` that store the raw integer string coming from source file : 
```ml
type pbinteger = {zvalue:Z.t; raw:string}
```
At pretyping, we convert this type back to `Z.t`, which mean that it does not affect the behavior of the compiler for all next compilation steps. Since `latex_printer` is executed before pre-typing, we can use the raw string for generating latex file. The new output is now : 
```tex
\jasminindent{2}tab[i] = 0xab;\\
```
* Add new Syntax Node `pbasedinteger` which dissapear at pretyping
* Changing parser …

Modifying jasmin2tex integer representation to fit source integer representation better

---

compiler/src/checkAnnot.ml
compiler/src/compile.ml
compiler/src/pretyping.ml
compiler/src/pretyping.mli
compiler/src/stackAlloc.ml

Remove a dead function, a legacy comment, and the now obsolete `tt_ws` function.

pretyping: small cleaning

---

CHANGELOG.md
compiler/src/varalloc.ml
compiler/tests/success/common/bug_870.jazz

varalloc: system calls do modify the stack pointer

---

CHANGELOG.md
compiler/safety/success/dynglob.jazz
compiler/safetylib/safetyAbsExpr.ml

checksafety: support dynamically scoped global variables

---

CHANGELOG.md
compiler/safety/success/lea.jazz
compiler/safetylib/safetyInterpreter.ml

Treats a LEA instruction as the identity or a cast.

checksafety: improve handling of LEA instruction

---

CHANGELOG.md
compiler/src/lexer.mll
compiler/src/syntax.ml
compiler/tests/success/common/integer_notation.jazz

Parsing integer in Jasmin compiler are quite limited for the moment. We can easily add more syntaxes by only modifying a few lines in the lexer : 
```jazz
reg u64 x,y,z;
x = 1_000_000_0000_0 //separating underscore for readability
y = 0b1110110 // binary 
z = 0o13671 // octal, supported by default by Z.of_string so there is no cost to add it
```
- modification of lexer to support those syntaxes

Add more integer notations for parsing 

---

compiler/src/coreIdent.mli

This allows polymorphic constant values of type 'a gvar.

Mark gvar OCaml type as covariant

---

proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v

Similarly to what is done with if statements, the instructions corresponding to the lowering of the condition inherit the instr-info from the complete statement.

x86-lowering: do not introduce dummy instr info

---

compiler/src/utils.ml

Best would be to avoid these dummy locations in the first place. Meanwhile, this is an attempt at saving the user from seeing scary locations.

Remove dummy locations from errors before printing them

---

CHANGELOG.md
compiler/src/printASM.ml
compiler/tests/success/common/bug_871.jazz

The `PrintASM.format_glob_data` function was able to write the same label multiple times, causing the produced assembly code to be incorrect. 
By adding a Map to count occurrences of the same variable, the problem is corrected.
There is a test to write (for example the file written by @vbgl in the issue). I wasn't sure where to put it so I didn't (We will need to add it before merging).

Debug of issue #871

---

.gitignore
.gitlab-ci.yml
compiler/config/tests.config
compiler/scripts/check-arm-m4
compiler/scripts/check-x86-64
compiler/scripts/extract-and-check
compiler/scripts/parse-print-parse

- Do not clutter the compiler/ directory with temp files: the test results are now in deterministic locations, in a file hierarchy under compiler/tests/results
- Tell easycrypt to use eclib from this repo.

Cleanup tests

---

CHANGELOG.md
compiler/config/tests.config
compiler/src/latex_printer.ml
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/syntax.ml
compiler/tests/fail/common/var_initialize_if.jazz
compiler/tests/fail/common/var_initialize_undecl.jazz
compiler/tests/success/common/variable_initialization.jazz

This is a duplicate of issue #899 based on #901 refactoring of pre-typing.
The feature requested is to add a new syntax that authorize variable initialization when they are declared.
The syntax is as follow :
```
reg u64 x=1,y=2,z,t=3;
```
With the proposed implementation, we can also initialize multiple variables at the same time: 
```jazz
reg u64 x=1,y=2,z,t=3;
```
The current implementation doesn't support array initializing with this feature because array can currently be explicitly created only at top level. Allowing it would require reworking a large part of the grammar and pre-typing analysis. 
In terms of semantic, the proposed implementation works as follow : 
```jazz
reg u64 x=3;
```
is abstractly equivalent to :
```jazz
reg u64 x;
x=3;
```

Variable intialization at declare time

---

scripts/coq-elpi.nix

Compiling Coq-elpi master with elpi 1.18.2 has been failing with:
~~~
File "src/coq_elpi_builtins_synterp.ml", line 1220, characters 21-28:
1220 |       ~scope ~dbname clauses ~depth ~options state)),
^^^^^^^
Error: This expression has type
(string option *
([> `After | `Before | `Remove | `Replace ] * string) option *
Elpi.API.Data.term)
list
but an expression was expected of type
(string option * ([ `After | `Before | `Replace ] * string) option *
Elpi.API.Data.term)
list
The second variant type does not allow tag(s) `Remove
~~~
Updating elpi to 1.20.0 works around this issue.
cc @gares (for your information).

CI/coq-master: use elpi 1.20.0

---

CHANGELOG.md
compiler/src/arm_arch_full.ml
compiler/src/pp_arm_m4.ml
compiler/tests/success/arm-m4/intrinsic_sbc.jazz
eclib/JModel_m4.ec
proofs/compiler/arm_instr_decl.v
proofs/compiler/arm_instr_decl_lemmas.v
proofs/compiler/arm_lowering.v
proofs/compiler/arm_lowering_proof.v

Using it is lowering is hard: the Jasmin semantics for the resulting carry flag does not match the ARM semantics…
Should we accept instructions like: `!c, x = y - z - !c;`?

ARM: add instruction SBC

---

CHANGELOG.md
compiler/src/latex_printer.ml
compiler/src/lexer.mll
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/syntax.ml
compiler/tests/fail/common/typealias_annotation_param.jazz
compiler/tests/fail/common/typealias_arrayelement.jazz
compiler/tests/fail/common/typealias_arrayelement_integer.jazz
compiler/tests/fail/common/typealias_duplicate.jazz
compiler/tests/fail/common/typealias_notfound.jazz
compiler/tests/success/arm-m4/typealias_armv7.jazz
compiler/tests/success/common/typealias.jazz
compiler/tests/success/x86-64/typealias_amd64.jazz

As described in #501, the objective of this feature is to allow declaration of type alias within jasmin syntax. The chosen keyword 'type' follow rust language specification. 
You can declare a type alias as follow :
``` 
type typename = u64;
type typename = u64[4];
type typename = othertypename;
``` 
types can then be called during variable declaration :
```
reg typename var;
reg typename[5] var;
``` 
This feature increase portability of programs. For example : 
``` 
// test.jazz
require "arch.jinc";
export fn inc(reg arch_type x) -> reg arch_type {
reg arch_type y;
y=x;
y+=1;
return y;
}
```
we can write a required header file that define arch_type (or even making it a part of compilation reserved types) for each targeted architecture.
```
// arch.jinc for x86_amd64 target
type arch_type …
```

Adding support for type definition

---

CHANGELOG.md
compiler/tests/success/x86-64/bug_895.jazz
proofs/compiler/x86_params.v

Do not use RAX to save the stack pointer on x86

---

CHANGELOG.md

Just a little correction of changelog where type alias feature was placed under 2024.07.1 bug fixes

moving type alias feature in changelog (probably moved during a merge)

---

proofs/arch/asm_gen.v
proofs/arch/asm_gen_proof.v
proofs/compiler/compiler_util.v
proofs/lang/utils.v

Fixes #949.
Do not hesitate to suggest more improvements to the error message.

asm-gen: improve “invalid scale” message

---

compiler/entry/commonCLI.ml
compiler/entry/commonCLI.mli
compiler/entry/jasmin2ec.ml
compiler/scripts/extract-and-check
compiler/src/glob_options.ml
compiler/src/main_compiler.ml
compiler/src/toEC.ml
compiler/src/toEC.mli
compiler/src/utils.ml
compiler/src/utils.mli

Was generating `require import JModel_x86` on ARM due to using `Glob_options`. Prevent from regressing by moving tests of extraction from `jasminc` to `jasmin2ec`.

Fix handling of the arch parameter in jasmin2ec

---

compiler/src/arch_full.ml
compiler/src/arch_full.mli
compiler/src/arm_arch_full.ml
compiler/src/pp_riscv.ml
compiler/src/printer.ml
compiler/src/regalloc.ml
compiler/src/regalloc.mli
compiler/src/riscv_arch_full.ml
compiler/src/stackAlloc.ml
compiler/src/varalloc.ml
proofs/compiler/arm_params.v
proofs/compiler/arm_params_proof.v
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/compiler/merge_varmaps.v
proofs/compiler/merge_varmaps_proof.v
proofs/compiler/riscv_decl.v
proofs/compiler/riscv_params.v
proofs/compiler/riscv_params_proof.v
proofs/compiler/x86_params.v
proofs/compiler/x86_params_proof.v
proofs/lang/expr.v
proofs/lang/one_varmap.v
proofs/lang/sem_one_varmap.v
proofs/lang/sem_one_varmap_facts.v

On RISC-V, the return address is read from register RA. This was not reflected in the model and generated wrong programs.
The `RAstack` case of return_address_location is given an additional optional argument `ra_return` that specifies what register to use (if any) when returning from a function. linearization is adapted to generate the right code. reg alloc and merge_varmaps take into account this potential new register.
I'm unsure of the changes I did. In particular, for linearization_proof, I have the impression that there is some kind of duplication between the semantics (ra_vm, ra_undef, ...) and the proof that introduces `killed_by_entry`, `killed_on_exit`, `killed_by_exit`. I managed to have a working version of the proof, but this may not be the principled one.
And the history is …

Risc-v: proper management of the return address

---

CHANGELOG.md
proofs/compiler/x86_instr_decl.v

x86: disallow BT with memory operands

---

CHANGELOG.md
compiler/examples/gimli/proofs/gimliv.ec
compiler/tests/success/x86-64/vector.jazz
eclib/JModel_x86.ec
eclib/JWord.ec
proofs/compiler/x86_instr_decl.v
proofs/compiler/x86_lowering.v
proofs/compiler/x86_lowering_proof.v
proofs/lang/expr.v
proofs/lang/sem_op_typed.v

- VPSRA only supports 16 or 32 bit elements
- count argument can be in xmm register or in memory

x86: improve description of AVX shift instructions

---

CHANGELOG.md
compiler/src/lexer.mll
compiler/tests/fail/common/newline_in_annotation_string.jazz
compiler/tests/sct-checker/reject.expected

A little correction for issue 943. We count the number of linebreaks inside annotation string and increment the variable by this amount

Patch for issue 943

---

compiler/entry/commonCLI.ml
compiler/entry/commonCLI.mli
compiler/entry/jasmin2ec.ml
compiler/entry/jasmin2tex.ml
compiler/entry/jasmin_ct.ml
compiler/tests/sct-checker/common.ml

There is no way of suppressing these warning in these tools. I also disabled the warnings for SCT checker tests. The tests under CCT don't need this since the warnings are already caught somewhere else.

Add nowarning option to jasmin-ct, jasmin2tex, and jasmin2ec

---

CHANGELOG.md
compiler/src/pp_arm_m4.ml
compiler/tests/success/arm-m4/far_global_access.jazz

Temporary patch for #619. I assume that `ADR` instructions are only generated for accesses to the data section, which seems to be true. I don't think it's a robust solution, but I don't see how to do it otherwise. Also, I believe we can't tell whether we can perform the relative access or not, so as to generate two instructions only when needed. The other options discussed in the issue didn't work, and I can't explain why.

Support far global variable accesses in ARM

---

CHANGELOG.md
compiler/src/compile.ml
compiler/src/conv.ml
compiler/src/conv.mli
compiler/src/liveness.ml
proofs/compiler/allocation.v
proofs/compiler/allocation_proof.v
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/inline.v
proofs/compiler/inline_proof.v

The tables used in allocation can be huge. We remove the dead variables from the tables, to reduce their sizes and speed up the pass. Inspired by CompCert that does something similar to reduce the cost of the value analysis.
Please review carefully the changes to Liveness, because I don't know what I did.
On [this implementation of Keccak](https://github.com/formosa-crypto/formosa-mldsa/tree/01ec03dd53e0fe43abf8c77091fd178560017ce6/src/libjade/keccakf1600), the time taken by the analysis after inlining goes down from 20s to 1.5s. It still feels too much for 4 inlined functions (size 1700, 3800 variables). (More functions are inlined, but these are the ones where the time is spent).

Use liveness info to speed up allocation

---

compiler/examples/jazzline/curve25519/common/add4/add4.jazz
compiler/src/toCL.ml

This merge request adds:
- add4.jazz example with abstract predicates and asserts/assumes that will result in a valid and correct cryptoline file
And does the following to these abstracts predicates:
- Uncomments `pow` abstract predicate for algebraic expressions
- Adds algebraic abstract predicate `b2i` that converts a boolean to an integer
- Add algebraic abstract predicate `u64i` that converts a u64 to an integer
- Predicate that allows comparing two boolean variables (uses `Obeq`)

Modified toCL to be able to run add4 ref example and added the add4 ref example

---

compiler/examples/jazzline/curve25519/common/add4/add4.jazz
compiler/examples/jazzline/curve25519/ref4/mul4/mul4_a24.jazz
compiler/src/toCL.ml

Depends on https://github.com/jasmin-lang/jasmin/pull/944.
This merge request adds:
- reduce4.jazz example with abstract predicates and asserts/assumes that will result in a valid and correct cryptoline file
And adds the following translations:
- CMOVcc
- MUL

 Modified toCL to be able to run mula24 ref example and added the mula24 ref example

---

compiler/entry/commonCLI.ml

This program
```
export
fn ble() {
reg u64 x = 0;
() = #spill(x);
x = 0;
() = #unspill(x);
}
```
with `jasmin-ct ble.jazz --compile lowering` produces
```
jasmin-ct: internal error, uncaught exception:
File "entry/jasmin_ct.ml", line 43, characters 15-21: Assertion failed
```

Propagate errors from compiler in CT checker

---

compiler/src/arm_arch_full.ml
compiler/src/dune
compiler/src/pretyping.ml
compiler/src/prog.ml
compiler/src/regalloc.ml
compiler/src/x86_arch_full.ml

Some warnings are disabled; enabling them is left as future work.

Dune: restore standard flags

---

compiler/src/checkAnnot.ml
compiler/src/checkAnnot.mli
compiler/src/main_compiler.ml
compiler/tests/fail/common/not-unrollable-for-loop.jazz
proofs/_CoqProject
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/post_unrolling_check.v

For loops must be gone after unrolling. The compiler relies on this fact. The no-for-loop check makes sure that if this is not the case, the user sees a proper error message.
Currently, this check is only run in the `jasminc` front-end. This PR moves this check to the compiler itself, where it belongs.

Check no for loop in coq

---

compiler/src/constraints.ml
compiler/src/sct_checker_forward.ml

This is a small performance optimization

SCT-checker: do not build a (large) list of booleans

---

compiler/src/latex_printer.ml

Add to the Jasmin project the `jasmin.sty` file needed when using the result of the `jasmin2tex` extraction.

Add message in the result of jasmin2tex about location of .sty file

---

CHANGELOG.md
compiler/src/latex_printer.ml

An empty blank line is meaningful in TEX. This fixes a regression introduced in #976 and also adds a changelog entry.

latex_printer: do not print a blank line

---

.gitlab-ci.yml

Something is wrong with CI. Who knows what…
This PR might help.

CI: disable the “cache dependencies” job

---

AUTHORS
CHANGELOG.md
compiler/src/toEC.ml

The EC extraction is wrong In the case of nested loop. Consider following Jasmin program:
```
param int a = 10;
fn __for_nest() -> ()
{
inline int i;
inline int j;
for i = 0 to (a + a)
{
for j = 0 to (a * a){}
}
return;
}
```
The result is currently :
```
require import AllCore IntDiv CoreMap List Distr.
from Jasmin require import JModel_x86.
import SLH64.
module M = {
proc __for_nest () : unit = {
var int:aux;
var j:int;
var i:int;
aux <- (10 + 10);
i <- 0;
while ((i < aux)) {
aux <- (10 * 10);
j <- 0;
while ((j < aux)) {
j <- (j + 1);
}
i <- (i + 1);
}
return ();
}
}.
```
It is not correct to use `aux` for the second loop.
This PR fix this. The result for the previous Jasmin example is now :
```
require import AllCore IntDiv CoreMap List Distr.
from Jasmin require import JModel_x86. …
```

Fix EC extraction in case on nested loops

---

compiler/src/checkAnnot.ml
compiler/src/checkAnnot.mli
compiler/src/main_compiler.ml
compiler/tests/fail/common/inline-remains.jazz
proofs/compiler/compiler.v
proofs/compiler/compiler_proof.v
proofs/compiler/post_unrolling_check.v

Check in Coq that #[inline]-annotated instructions are gone after unrolling

---

proofs/lang/utils.v

For https://github.com/coq/coq/pull/19997

Require Ztac to use it in lang/utils.v (for coq/coq#19997)

---

default.nix

Temporary fix for the `coq-master` job.

CI/coq-master: pin stdlib

---

CHANGELOG.md
compiler/src/x86_arch_full.ml
compiler/tests/success/x86-64/vpblendvb.jazz
eclib/JModel_x86.ec
proofs/compiler/x86_instr_decl.v
proofs/lang/word.v

This intrinsics covers the following AVX instructions:
- VPBLENDVB (using suffixes 16u8 and 32u8)
- VBLENDVPS (using suffixes 4u32 and 8u32)
- VBLENDVPD (using suffixes 2u64 and 4u64)
This new intrinsic subsumes #VPBLENDVB which is therefore deprecated.

x86: add BLENDV intrinsics

---

compiler/entry/jasmin_ct.ml
compiler/src/compile.ml
compiler/src/compile.mli
compiler/src/sct_checker_forward.ml
compiler/src/sct_checker_forward.mli
compiler/tests/sct-checker/common.ml
proofs/compiler/lower_spill.v
proofs/lang/extraction.v

The aim is to simplify the implementation of the SCT checker by requiring that the program to be analyzed does not use any `#spill` or `#unspill` pseudo-operator. This pre-condition is straightforward to achieve, given the availability of the “lower-spill” compilation pass. For convenience the first commit makes available a convenient interface to this program transformation.

SCT: drop support for implicit spilling

---

eclib/JWord.ec

This PR does two (independent) minor fixes to `JWord.ec` (unsure if it should be split into two PRs).
The first one is to add the newly supported`[rigid]` tag to the hints dealing with `modulus` (abbreviation of `2^size`). The feature was added to EC#main in https://github.com/EasyCrypt/easycrypt/commit/5f7be80cc247e5ad91606e139b9b20c30be91d3c) in order to solve efficiency issues when the `BitWord` theory is instantiated with big sizes (e.g. 512). It was tested on MLKEM, where the issue was detected, and apart from solving the efficiency problem that prompted the additional feature, it had no further impact on the whole proof. But it is true that the behavior concerning those hints has changed slightly, so it has the potential to trigger some backward compatibility issues (although, I …

minor fix in JWord.ec

---

CHANGELOG.md
compiler/safetylib/safetyPreanalysis.ml
compiler/src/conv.ml
compiler/src/liveness.ml
compiler/src/pretyping.ml
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/ssa.ml

PR corresponding to proposition of [#1016](https://github.com/jasmin-lang/jasmin/issues/1016)

Adding info to function

---

CHANGELOG.md
compiler/src/pretyping.ml
compiler/src/utils.ml
compiler/src/utils.mli

Some well typed programs are rejecting by pre-typing because they don't have a valid assembly target (see [#727](https://github.com/jasmin-lang/jasmin/issues/727))
I introduced a global boolean variable (I know it isn't the cleanest but it fit well in this case) that define if some of pre-typing error should be handled as warning or as error. It can be set with the `Utils.set_warn_recoverable` function.

Changing some prettyping errors to be able to ignore them (preparation to fix bug #727)

---

compiler/src/utils.ml
compiler/src/utils.mli

The following functions have been removed:
^~, -|
List.opicki, List.smart
pp_if, pp_maybe, pp_maybe_paren
as_seq4, as_seq5, as_seq6, as_seq7
fst_map, snd_map
timed
The following function has been removed from the .mli
pp_enclose

Utils: remove dead functions

---

compiler/src/location.ml
compiler/src/location.mli

The following functions have been removed
mergeall
unlocs
lmap
locate_error
set_loc
set_oloc
The exception LocError has been removed

Location: remove dead code

---

compiler/scripts/check-risc-v

This makes it possible to run the RISC-V checks without Bash.
Side-note: changing the name of the assembler depending on the OS kernel is wrong.
Reported by Alexandre (@MrDaiki).

check-risc-v: avoid non-POSIX (bash) constructions

---

compiler/src/pretyping.ml
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/subst.ml

Removes `Prog.clamp_pe` and `Subst.clamp_k`, and in `Pretyping.ml`: `check_lval_pointer`, `is_constant`, `tt_as_bool`, `tt_as_int`, `tt_as_word`, and the exception `NotAPointer`.

OCaml: remove dead code

---

CHANGELOG.md
compiler/src/regalloc.ml

Regalloc: improve printing of equiv. traces

---

proofs/arch/asm_gen.v
proofs/arch/asm_gen_proof.v
proofs/compiler/arm_stack_zeroization_proof.v
proofs/compiler/riscv_stack_zeroization_proof.v
proofs/compiler/tunneling_proof.v
proofs/compiler/x86_stack_zeroization_proof.v

Mathcomp now includes `onth` and related lemmas: https://github.com/math-comp/math-comp/pull/1318.
Fixes #1036.

Make compatible with current mathcomp

---

.gitlab-ci.yml
compiler/examples/extraction-unit-tests/.gitignore
compiler/examples/extraction-unit-tests/Makefile
compiler/examples/extraction-unit-tests/ec.config
compiler/examples/extraction-unit-tests/loops.jazz
compiler/examples/extraction-unit-tests/proofs.ec

This is a first step addressing #994 and an invitation to contribute more unit tests.
This PR adds two cases related to bugs recently fixed.
Writing EasyCrypt proof scripts that are compatible with current and next versions of EasyCrypt is challenging.

EC: add unit tests for extraction

---

CHANGELOG.md
compiler/src/printer.ml

[PR#969](https://github.com/jasmin-lang/jasmin/pull/969) introduced a bug in `pp_iprog` function which was not priting added info in CWhile. This PR fix it

updating printer `pp_iprog` function to print Cwhile Info

---

compiler/examples/gimli/proofs/gimliv.ec

Recent changes (since yesterday, maybe https://github.com/EasyCrypt/easycrypt/pull/708) in EasyCrypt development branch made this proof fail. Bugfix or regression?

Gimli proof: fix for latest EasyCrypt

---

CHANGELOG.md
compiler/src/latex_printer.ml
compiler/src/pretyping.ml
compiler/src/syntax.ml
compiler/tests/fail/common/storage_signature_mismatch.jazz
compiler/tests/success/common/bug_607.jazz
compiler/tests/success/x86-64/test_ptr_fn_inline.jazz

Compiler wasn't checking coherence of storage types between declared return storage type and return variable storage type. For more informations see #18 
Defining a new function in `pre-typing` to check for this.
This change break retrocompatibility making some old program not valid. (some tests of the test suite had to be modified)
Fixes #18

Fixing type checking of function return storage type

---

CHANGELOG.md
compiler/src/intervalGraphColoring.ml
compiler/src/varalloc.ml
compiler/tests/fail/stack_allocation/x86-64/uninit_stack.jazz
compiler/tests/success/x86-64/bug_680.jazz

Some variables are dead: they are written but never read back. This happens in particular when the source program uses “intrinsics” that are by design kept until assembly, even if they could be otherwise considered dead.
To properly compile programs with such dead stack variables, this makes two changes.
1. stack sharing (aka varalloc) uses weak liveness analysis that computes a singleton (e.g., [x; x]) live-range for dead variables.
2. graph-coloring extends these live ranges (e.g., to [x; x+1]) to be able to handle them properly.
Fixes #680

Fix allocation of dead stack variables

---

CHANGELOG.md
proofs/compiler/x86_instr_decl.v

x86: fix printing of CLFLUSH instruction

---

eclib/JWord.ec

It started failing when I upgraded to the latest easycrypt release.

Fix failing smt in proof of JWord.bits_divmod

---

CHANGELOG.md
compiler/src/label_check.ml
compiler/src/label_check.mli
compiler/src/main_compiler.ml
compiler/tests/success/common/inline_label_duplication.jazz

Assembly generation use `PrintCommon.escape` function to build labels which can creates names conflicts because of namespaces. see (#993).
We introduce a map in `pretyping.ml` environment that check if a label is already used by another function.

Adding a check to verify that functions names do not conflict when translated to assembly labels

---

CHANGELOG.md
compiler/src/pretyping.ml

Introduction of operators `BLENDV` and `MOVEMASK` made `VPBLENDVB` and `VPMOVMSKB` deprecated. This PR add a warning to signal it. 
For genericity reasons, this is done during pre-typing step of compilation.

Updating pre-typing to detect deprecated intrinsic operators

---

proofs/3rdparty/ssrring.v
proofs/_CoqProject
proofs/arch/arch_extra.v
proofs/compiler/linearization_proof.v
proofs/lang/extraction.v
proofs/lang/psem_defs.v
proofs/lang/sem_one_varmap.v
proofs/lang/sem_type.v
proofs/lang/strings.v
proofs/lang/type.v
proofs/lang/varmap.v

Now that we dropped support for < 8.20, we can make a bit of cleaning.
Also removes some warning in 9.0.

Update warnings (v2)

---

compiler/src/compile.ml
compiler/src/conv.ml
compiler/src/ct_checker_forward.ml
compiler/src/fInfo.ml
compiler/src/latex_printer.ml
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/printer.ml
compiler/src/prog.ml
compiler/src/prog.mli
compiler/src/sct_checker_forward.ml
compiler/src/subst.ml
compiler/src/syntax.ml
proofs/compiler/linearization.v
proofs/compiler/linearization_proof.v
proofs/lang/expr.v
proofs/lang/extraction.v

Partially addresses #777.
The main change is that linearization no longer introduces any `dummy_instr_info`.

Attach proper location to function prologue & epilogue

---

CHANGELOG.md
compiler/safetylib/safetyPreanalysis.ml

In the safety pre-analysis, a set of expressions is represented by a list (without duplicates). Duplicates are tolerated during the construction of the list which is normalized at the end of the pre-analysis.
This runs normalization more often so as to prevent the size of this list to blow-up.

Checksafety: normalize often the list of if-conditions

---

scripts/test-libjade.sh

This enables the use of `jasmin2ec` in libjade without breaking jasmin CI.

CI/libjade: expose jasmin2ec

---

compiler/src/regalloc.ml
proofs/arch/arch_decl.v
proofs/arch/arch_extra.v
proofs/compiler/arm_extra.v
proofs/compiler/riscv_extra.v
proofs/compiler/x86_extra.v
proofs/compiler/x86_params_proof.v
proofs/lang/sopn.v

Some x86 instructions have a mandatory explicit operand XMM0 (e.g. SHA256RNDS2)
Some ARM instructions only accept registers in the [r0; r7] range (e.g., MULS)

Generalize forced explicit registers in instr. descriptors

---

compiler/src/debugInfo.ml
compiler/src/ppasm.ml

A little change to the way pretty printing of debug is handled. Without this change, arm and riscv assembly pretty printing return add an empty line after printing of debug info. This PR remove it while maintaining x86 pretty printing behaviour.

Changing assembly debug info pretty printing for coherence between all printers

---

compiler/src/pp_x86.ml

As stated by [GAS doc](https://sourceware.org/binutils/docs/as/Global.html), `.globl` and `.global` are equivalent. Yet we use `.globl` for x86 and `.global` for arm and riscv. This PR make all headers use `.global`. This will help to factor assembly printing

changing .globl to .global in pp_x86 for simplification

---

compiler/src/main_compiler.ml
compiler/src/pretyping.ml
compiler/src/printCommon.ml
compiler/src/printCommon.mli
compiler/src/printFexpr.ml
compiler/src/printer.ml
compiler/src/printer.mli
compiler/src/regalloc.ml
compiler/src/subst.ml

- do not print ` /* of uXX */` for casts if not debug
- do not print ` (defined at loc)` for vars if not debug
The goal is to hopefully get more readable error messages by default, and a more verbose one if `-debug` is given to the command line.

Be less verbose if not debug

---

CHANGELOG.md
compiler/src/pp_arm_m4.ml
compiler/src/pp_riscv.ml

Currently, we have two different behaviour regarding the position of `.global` directive in generated assembly sources. In x86, we put them at the top of the file. In arm and riscv, we put them just before the function label.
This PR modify the behaviour of arm and riscv assembly printer to put `.global` directives after file header like it is done in x86. This will increase readability of generated assembly and improve coherence between generated assembly for all architectures.
The doc only specify that export directive should be placed before function label, so this change shouldn't break anything (documentation of this feature is however lacking).

Putting .global (export) directive at top of generated assembly (for coherence)

---

CHANGELOG.md
compiler/src/pp_riscv.ml

Currently, Arm and x86 assembly printers use a common function `format_globs_data` to print the content of the data segment. This function is not used by riscv printer. This PR make the riscv printer use it.

Changing risc-v assembly data segment printer

---

proofs/compiler/arm_stack_zeroization_proof.v
proofs/compiler/riscv_stack_zeroization_proof.v
proofs/compiler/stack_alloc_proof.v
proofs/compiler/x86_stack_zeroization_proof.v
proofs/lang/memory_model.v

https://github.com/math-comp/math-comp/pull/1256 changes the behavior of rewrite (seemingly because it generalizes some operations). This PR makes the necessary changes to keep compiling. `lia` also does not like at all the change in the hierarchy.

Adapt to MC#1256

---

CHANGELOG.md
compiler/src/AsmTargetBuilder.ml
compiler/src/AsmTargetBuilder.mli
compiler/src/pp_arm_m4.ml
compiler/src/pp_riscv.ml
compiler/src/pp_x86.ml

This PR introduce a new module `AsmTarget` which abstract traversal of assembly program during the printing pass. It has been tested for all supported architectures on libjade and common test file without provoking any change to generated assembly.

Factoring behaviour of assembly printer in a functor module

---

compiler/Makefile
compiler/config/tests.config
compiler/safety/dune
compiler/safety/fail/carry_flags_err.jazz
compiler/safety/fail/carry_flags_err2.jazz
compiler/safety/fail/load.jazz
compiler/safety/fail/loop2.jazz
compiler/safety/run.expected
compiler/safety/run.ml
compiler/safety/success/bounded_while.jazz
compiler/safety/success/carry_flags.jazz
compiler/safety/success/loop1.jazz
compiler/safety/success/loop3.jazz
compiler/safetylib/safetyInterpreter.ml
compiler/safetylib/safetyInterpreter.mli
compiler/scripts/check-safety
compiler/src/main_compiler.ml
compiler/src/x86_safety.mli

The outputs of the checker on the test suite are now saved. This makes it easier to spot regression, in particular to be sure that failing tests actually fail for the expected reason (and no due to e.g., a syntactic error).

safety: use dune to run tests

---

compiler/src/toEC.ml

ToEc.ml file `EnvT.t` declare a `glob` field but doesn't use it anywhere. I removed it

remove glob field from ec env

---

compiler/src/pretyping.ml
compiler/src/utils.ml
compiler/src/utils.mli

- Add `Utils.remove_warning` to silence a specific warning category
- Introduce `InlinedCallToExport` category to make it possible to silence the warning that an export function is inlined at every call site.

Small improvement to warnings

---

.gitlab-ci.yml
compiler/Makefile
compiler/examples/extraction-unit-tests/Makefile

Removes the legacy [byte], [native], and [build] targets, and the [do-build] function.
The `byte` and `native` targets have been made identical in #838.
~Question: does it make sense to have both `build` and `all` targets or should they be merged?~

Makefile: small cleaning

---

compiler/dune-project
compiler/safetylib/dune
compiler/src/dune

This PR replace version of dune used by the compiler from 3.0 to 3.7. This will allow the usage of new features such as qualify subdirs. I also add to make dune ignore warning 67 because it was detected with this new version.

Changing dune version to 3.7

---

compiler/examples/extraction-unit-tests/Makefile

So that we don’t have to add the file name (twice) in the makefile when adding a new test case.

Extraction tests: clean Makefile

---

compiler/src/printCommon.mli
opam
proofs/_CoqProject

With mathcomp 2.4, we get a lot of warnings of the form
```
Notation ringType is deprecated since mathcomp 2.4.0.
Try pzRingType (the potentially-zero counterpart) first, or use nzRingType instead.
```
This is not possible to solve without requiring 2.4.0, so for the moment, warnings are silenced.

Support mathcomp 2.4

---

CHANGELOG.md
compiler/src/sct_checker_forward.ml
compiler/tests/sct-checker/fail/bug_1179.jazz
compiler/tests/sct-checker/reject.expected

SCT checker: ignore annotations on local variables

---

proofs/compiler/riscv_lower_addressing_proof.v

The Coq proof has been broken since the merge of #1191 (cc @eponier @bgregoir).

Fix in riscv_lower_addressing_proof

---

compiler/src/main_compiler.ml
compiler/src/utils.mli

There is no need to run any analysis nor check when the results are going to be discarded.

Run the linter only when Linter warnings are enabled

---

.gitlab-ci.yml
compiler/MANIFEST
compiler/Makefile
compiler/dune-project
compiler/jasmin.opam
opam

Alternative to https://github.com/jasmin-lang/jasmin/pull/1210
In this PR, `compiler/jasmin.opam` is distributed with the extracted OCaml and only makes sense there, in the same spirit as `compiler/Makefile.compiler`.

Improvements to the opam files, second try

---

compiler/jasmin.opam
opam

Publishing the latest version of jasmin to opam (https://github.com/ocaml/opam-repository/pull/28116) and playing with it revealed a few bugs.

opam: fix bounds and install command

---

compiler/src/pretyping.ml
compiler/tests/fail/linter/dead_variables.jazz
compiler/tests/warnings.t

When elaborating `?{…}`, give names to implicit flags only when they are used in combinations.

Pretyping: introduce implicit flags only when needed

---

docs/source/conf.py

Current value is “default” which puts random inconsistent decorations.

Docs: set default highlight-language to “none”

---

.gitlab-ci.yml

Let’s make the `coq-proof` job be picky when choosing the CI VM.

CI: tag the coq-proof job

---

CHANGELOG.md
compiler/src/regalloc.ml
compiler/tests/success/arm-m4/large_stack/large_stack_return_address.jazz

with a large stack frame and the return address passed on the stack
First reported by @xvzcf

Linearization generates correct code

---

compiler/src/pp_arm_m4.ml

I would like to get a warning when we add a new instruction and we forget to check that its arguments are valid.

Make pp_arm_m4 check exhaustive

---

compiler/src/compile.ml
compiler/src/regalloc.ml
compiler/src/regalloc.mli
compiler/src/stackAlloc.ml

Extracts two subroutines from the register allocation pass:
- a pre-processing step that creates fresh variables to compute and store the return addresses;
- a post-processing step that builds the “oracle” for stack allocation.
This makes it easier to reuse these steps and slightly decreases complexity (smaller functions, less arguments).

Regalloc: small refactoring

---

eclib/JWord.ec

Hi, the CI check of the latest EC commit [failed](https://github.com/EasyCrypt/easycrypt/actions/runs/17068200471/job/48403958178) for the new lemma `to_uintBb`. Also, I ran JWord.ec on my laptop, and I failed at `to_uintBb` too. The reason is probably the instability of SMT solving. So, I rewrote the proof to unburden the SMT solver.
I found that the CI check failed after I contributed to EasyCrypt for the first time. I felt a bit embarrassed. I hope this PR can make the CI of EasyCrypt work again. Thanks :)

eclib: lightweight proof for to_uintBb

---

CHANGELOG.md
compiler/src/x86_arch_full.ml
compiler/tests/printing.ml
compiler/tests/success/x86-64/lzcnt.jazz
eclib/JModel_x86.ec
eclib/JWord.ec
proofs/compiler/x86_instr_decl.v

The first commit is unrelated but proved itself useful in debugging the instruction descriptor.
This instruction has a safety precondition: its argument should not be zero, since the result is undefined in this case.

Add x86 instruction BSR

---

.gitignore
Makefile.compiler
eclib/Makefile

This make it possible for EasyCrypt (next version) to automatically detect the installed Jasmin library (without extra configuration step by the user).

eclib: install a configuration file

---

.github/pull_request_template.md
CHANGELOG.md
changes/01-feature/00000-title.md
changes/02-bugfix/00000-title.md
changes/03-other/00000-title.md
changes/04-documentation/00000-title.md
changes/README.md
scripts/generate-release-changelog.sh

Alternative to https://github.com/jasmin-lang/jasmin/pull/1236
This is a POC of a design to avoid stupid merge conflicts involving the changelog. It relies on a simple script taken from https://github.com/math-comp/math-comp.
Instead of editing CHANGELOG.md, PRs have to create a file `<PR number>-some-text.md` in a sub-directory of `changes`, depending on the kind of changes done by the PR, where <PR number> is the PR number. I create the same categories as in https://github.com/jasmin-lang/jasmin/pull/1236.
Before doing a release, one should type `./changes/generate-release-changelog.sh`. It will generate a file called CHANGELOG_UNREALEASED.md that the release manager should insert inside CHANGELOG.md.

POC: updating the changelog with a script

---

changes/02-bugfix/1273-less-dead-warnings.md
compiler/linter/Checker/DeadVariables.ml
compiler/src/prog.ml
compiler/src/prog.mli
compiler/tests/fail/linter/bug_1223.jazz
compiler/tests/warnings.t

1. Instructions that do not assign any variable cannot raise a “dead assignment” warning.
2. Instructions that only assign dead variables are bogus only if they have no other “effect” (function call, memory store).

Linter: less false alarms about dead assignments

---

changes/03-other/1185-decl-init.md
compiler/examples/extraction-unit-tests/loops.jazz
compiler/src/latex_printer.ml
compiler/src/parser.mly
compiler/src/pretyping.ml
compiler/src/syntax.ml
compiler/tests/sct-checker/success/paper.jazz
compiler/tests/success/common/variable_initialization.jazz
compiler/tests/success/x86-64/vpblendvb.jazz
docs/source/language/syntax/code.md
docs/source/language/syntax/index.md

In any given declaration sequence, either no variable is initialized,
and declarations may be separated by space or comma,
or *all* variables are initialized and are separated by a mandatory
comma.

Stricter syntactic rules for initializing variables at declaration time

---

AUTHORS
changes/01-feature/1123-export-json.md
compiler/src/glob_options.ml
compiler/src/main_compiler.ml
compiler/src/printExportInfo.ml
compiler/src/printExportInfo.mli
compiler/src/printer.ml
compiler/src/utils.ml
compiler/src/utils.mli

Add option `-print-export-info` to print interesting information of export functions.
For the moment it only prints the alignment of the arguments for each exported function.

Add option to print export information

---

eclib/Makefile

Option "-t" may not be supported by non-GNU install

install: use portable options

---

.gitlab-ci.yml

Should we run the test-suite as part of the CI⸮

CI: run RISC-V extraction tests

---

changes/03-other/1283-useless-extension.md
compiler/src/pretyping.ml
compiler/tests/warning/x86-64/ignored_zero_extension.jazz
compiler/tests/warnings.t

We detect trivially useless zero-extensions of primitives (the size of the extension is the same as the size of the output of the primitive), drop them and produce a warning.

Ignores useless zero-extensions of primitives
