proofs/compiler/constant_prop_proof.v, proofs/compiler/lowering_proof.v, proofs/compiler/x86_instr.v, proofs/compiler/x86_sem.v, proofs/lang/psem.v, proofs/lang/sem.v
Minor work. Allow to compile under Coq 8.8.2 and 8.7.2
=> solve breaking 8.8.2 + alignment

compiler/src/alias.ml, compiler/tests/fail/range_overflow.jazz
=> subarrays: improved error message

eclib/JModel.ec
Semantics for horizontal addition, VPMADDWD & VPMADDUBSW instructions.
=> EC semantics for PMADDWD & PMADDUBSW instructions

compiler/tests/success/vpblendvb.jazz, compiler/tests/success/vptest.jazz, eclib/JModel.ec, proofs/compiler/x86_instr_decl.v, proofs/lang/word.v
Add 2 new AVX2 instructions w/ Coq semantics and unit tests.
=> Add VPTEST and VPBLENDVB

compiler/src/pretyping.ml
=> pretyping: improve location information in warnings

compiler/src/regalloc.ml
See: https://github.com/jasmin-lang/jasmin/issues/87
=> regalloc: fail with a nice error message when a “forced” variable is not subject to allocation (inline, stack, etc)

proofs/arch/arch_extra.v, proofs/arch/asm_gen_proof.v, proofs/compiler/dead_code_proof.v, proofs/compiler/linearization_proof.v, proofs/compiler/lowering_proof.v, proofs/compiler/makeReferenceArguments.v, proofs/lang/array.v, proofs/lang/memory_example.v, proofs/lang/strings.v, proofs/lang/type.v, proofs/lang/utils.v, proofs/lang/wsize.v
Commits are independent but might be squashed together.
=> Remove some dead code

compiler/README.md, opam, scripts/coqword.nix
When I did the change of license, I forgot to update a bunch of places. I'll backport this to release-21.
=> MIT everywhere

AUTHORS, CHANGELOG.md
When preparing the release, I realized I had missed one change and one author. I'll force-push the release branch to take that commit into account.
=> Last fixes before the release

.gitlab-ci.yml, compiler/opam, default.nix, scripts/opam-setup.sh
To make it easier to just `opam install` the jasmin compiler.
=> Opam file for the Jasmin compiler

.gitlab-ci.yml, compiler/opam, default.nix, eclib/JModel.ec, scripts/easycrypt.nix, scripts/nixpkgs.nix, scripts/opam-setup.sh
This cherry-picks a few commits from the main branch.
=> release-21: port recent updates to the CI

eclib/JModel.ec
Let’s keep the various branches in sync.
=> eclib: addc & zlog2

eclib/JModel.ec
Fixes part of #130.
Tiago, would you like to test, please?
TODO
=> eclib: add notations for sub-borrow

.gitlab-ci.yml, default.nix, scripts/test-libjade.sh
=> CI: exeunt cryptolib tests; enter libjade test

CHANGELOG.md, compiler/src/arch_full.ml, compiler/src/arch_full.mli, compiler/src/glob_options.ml, compiler/src/main_compiler.ml, compiler/src/stackAlloc.ml, compiler/src/x86_arch_full.ml, compiler/tests/success/call_conv_windows.jazz, proofs/arch/arch_decl.v, proofs/arch/arch_sem.v, proofs/arch/asm_gen.v, proofs/arch/asm_gen_proof.v, proofs/compiler/arch_params_proof.v, proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v, proofs/compiler/linearization.v, proofs/compiler/linearization_proof.v, proofs/compiler/merge_varmaps.v, proofs/compiler/merge_varmaps_proof.v, proofs/compiler/x86_decl.v, proofs/compiler/x86_params.v, proofs/compiler/x86_params_proof.v, proofs/lang/extraction.v, proofs/lang/linear_sem.v, proofs/lang/one_varmap.v, proofs/lang/sem_one_varmap.v, proofs/lang/sem_one_varmap_facts.v, proofs/lang/var.v
This is the first step, next step is to add calling convention in Coq. So we can wait for the merge.
=> linear and one_varmap do not depend on arch anymore

compiler/opam, compiler/src/ct_checker_forward.ml, compiler/src/pretyping.ml, compiler/tests/success/subroutines/literal-argument.jazz, opam
Three unrelated changes:
- remove dead code (in CT checker)
- improve the `opam` files
- do not crash when inline function calls get non-trivial arguments
=> Minor improvements

.gitlab-ci.yml, default.nix, eclib/JWord.ec, scripts/easycrypt.nix, scripts/nixpkgs.nix
~This is not ready as it needs some fix in `eclib/`~
I’ve just fixed the `eclib`. An EasyCrypt guru may want to suggest a better patch.
=> CI: also test eclib against next EasyCrypt (main)

compiler/src/printLinear.ml, proofs/arch/arch_decl.v, proofs/arch/arch_sem.v, proofs/arch/asm_gen.v, proofs/arch/asm_gen_proof.v, proofs/compiler/linearization_proof.v, proofs/compiler/tunneling_proof.v, proofs/compiler/x86_sem.v, proofs/lang/linear.v, proofs/lang/linear_sem.v
=> Linear: add Call and Return instructions

CHANGELOG.md, compiler/tests/success/bug_224.jazz, proofs/lang/extraction.v
=> Correctly extract dummy instr_info to 1 (one)

proofs/arch/asm_gen.v, proofs/arch/asm_gen_proof.v, proofs/compiler/lea.v, proofs/compiler/lea_proof.v, proofs/compiler/x86_lowering.v, proofs/compiler/x86_lowering_proof.v
This makes the data-type independent of the target architecture
=> lea: use Z instead of pointer

compiler/src/pretyping.ml
=> Fix typo in pre-typing

scripts/easycrypt.nix
See https://github.com/EasyCrypt/easycrypt/pull/257
=> easycrypt: add dependency to “camlp-streams”

proofs/compiler/compiler.v, proofs/compiler/linearization.v, proofs/compiler/linearization_proof.v, proofs/compiler/x86_params.v, proofs/compiler/x86_params_proof.v
=> Generalize linearization parameters to be partial

compiler/src/evaluator.ml, compiler/src/evaluator.mli, compiler/src/main_compiler.ml, compiler/src/pretyping.ml, compiler/tests/fail/evaluator/arity.jazz, compiler/tests/fail/evaluator/return-undef.jazz
This slightly improves error messages
=> OCaml Evaluator: accept arguments & instr-info

CHANGELOG.md, compiler/src/toEC.ml
=> toEC/CT: fix zero-extended intrinsics

CHANGELOG.md
Just a matter of having a consistent style. Do not hesitate to tweak the PR as you like.
=> Make the CHANGELOG cleaner

proofs/compiler/arm_params_proof.v
If anyone has an explanation or a better fix, please share it!
=> Fix for Coq 8.16

compiler/opam, opam
=> Raise versions of OCaml and batteries

compiler/opam, opam
This is a partial backport of https://github.com/jasmin-lang/jasmin/pull/265.
=> Raise the version of batteries

proofs/_CoqProject, proofs/compiler/allocation.v, proofs/compiler/allocation_proof.v, proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v, proofs/compiler/inline.v, proofs/compiler/inline_proof.v
I removed the functors and used typeclasses instead. I mostly copy-pasted the code, but without understanding everything, maybe there were opportunities to simplify the code that I didn't see.
=> Split allocation into code + proof

proofs/compiler/arm_lowering.v, proofs/compiler/arm_lowering_proof.v
Source-level `>>s 0` are translated to a plain `MOV` rather than an invalid `ASR … #0`.
=> arm: do not emit right shifts with null amount

compiler/jasmin.mlpack.in, compiler/src/evaluator.ml, compiler/src/insert_copy_and_fix_length.ml, compiler/src/ppasm.ml, compiler/src/pretyping.ml, compiler/src/printCommon.ml, compiler/src/printCommon.mli, compiler/src/printLinear.ml, compiler/src/printer.ml, compiler/src/printer.mli, compiler/src/regalloc.ml, compiler/src/safety/safetyAbsExpr.ml, compiler/src/safety/safetyInterpreter.ml, compiler/src/stackAlloc.ml, compiler/src/subst.ml, compiler/src/toEC.ml, compiler/src/typing.ml
This removes the dependency between Printer and PrintLinear modules.
=> Refactor printers

CHANGELOG.md, compiler/src/regalloc.ml, compiler/tests/fail/register_allocation/bug_309.jazz
=> regalloc: flag registers may conflict

proofs/compiler/compiler_proof.v
For the sake of purity of the compilation log⸮
=> compiler-proof: get rid of a warning

.gitlab-ci.yml, compiler/config/tests.config, compiler/scripts/check-arm, default.nix
This highlights some issues in the compiler.
=> CI: test compilation to ARMv7-m4

CHANGELOG.md, compiler/tests/fail/array_expansion/bug_333.jazz, compiler/tests/fail/array_expansion/out-of-bounds.jazz, proofs/compiler/array_expansion.v, proofs/compiler/array_expansion_proof.v
=> Check bounds in array-expansion

CHANGELOG.md, compiler/src/latex_printer.ml, compiler/src/parser.mly, compiler/src/toEC.ml, compiler/tests/success/clflush.jazz, compiler/tests/success/fences.jazz, proofs/compiler/x86_instr_decl.v
Draft until there is agreement on the concrete syntax.
=> Add x86 instructions CLFLUSH, LFENCE, MFENCE, SFENCE

proofs/compiler/allocation_proof.v, proofs/compiler/array_copy_proof.v, proofs/compiler/array_expansion_proof.v, proofs/compiler/array_init_proof.v, proofs/compiler/constant_prop_proof.v, proofs/compiler/dead_calls_proof.v, proofs/compiler/dead_code_proof.v, proofs/compiler/inline_proof.v, proofs/compiler/linearization_proof.v, proofs/compiler/makeReferenceArguments_proof.v, proofs/compiler/merge_varmaps_proof.v, proofs/compiler/propagate_inline_proof.v, proofs/compiler/remove_globals_proof.v, proofs/compiler/stack_alloc_proof_2.v, proofs/compiler/tunneling_proof.v, proofs/compiler/unrolling_proof.v, proofs/compiler/x86_lowering_proof.v, proofs/compiler/x86_params_proof.v, proofs/lang/expr_facts.v, proofs/lang/psem.v, proofs/lang/psem_facts.v, proofs/lang/psem_of_sem_proof.v, proofs/lang/sem_one_varmap_facts.v
This is part of the task about improving how we handle parameters (#338), as a separate PR to ease reviewing.
=> Remove some unnecessary @s and implicit parameters

proofs/arch/arch_decl.v, proofs/arch/arch_extra.v, proofs/compiler/stack_alloc.v, proofs/compiler/tunneling_proof.v
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/772355783
=> Remove some dead lemmas

default.nix
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/766776198
=> default.nix: use Coq 8.16

compiler/tests/success/cmove8.jazz, compiler/tests/success/divmod.jazz, compiler/tests/success/extend.jazz, compiler/tests/success/pointers/test_spill_loop.jazz, compiler/tests/success/refmod.jazz, compiler/tests/success/subarrays/test2.jazz, compiler/tests/success/test_add.jazz, compiler/tests/success/test_glob_array_256.jazz, compiler/tests/success/test_glob_array_while.jazz, compiler/tests/success/test_glob_array_while1.jazz, compiler/tests/success/test_glob_array_while2.jazz, compiler/tests/success/test_inline_in_loop.jazz, compiler/tests/success/unroll_nested_loop.jazz, compiler/tests/success/vpcmp.jazz
I wished all test cases could be automatically verified for safety. It’s not the case yet, but this PR is a step towards this goal.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/758179917 (failed…)
=> Tests: some cleaning

scripts/easycrypt.nix
Fix build of development version of EasyCrypt after https://github.com/EasyCrypt/easycrypt/commit/294e2a64a696bc9c062c93adfa7c8511495184e6
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/779382400
=> [CI] EasyCrypt: build with Dune 3

compiler/src/pp_arm_m4.ml
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/785407903
=> ARM: mark the export functions as .global

compiler/.merlin, compiler/entry/jasminc.ml, compiler/jasmin.mlpack.in, compiler/src/compile.ml, compiler/src/compile.mli, compiler/src/coreArchFactory.ml, compiler/src/coreArchFactory.mli, compiler/src/insert_copy_and_fix_length.ml, compiler/src/insert_copy_and_fix_length.mli, compiler/src/main_compiler.ml
This extracts reusable bits from `mail_compiler.ml`.
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/784495107
=> Refactoring of the Main_compiler module and small related changes

scripts/opam-setup.sh
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/792407686
=> CI: use OCaml 4.14.1 in opam jobs

CHANGELOG.md, compiler/safety/fail/init-join.jazz, compiler/safety/success/align2.jazz, compiler/src/safety/domains/safetyBoolean.ml, compiler/src/safety/domains/safetyInterfaces.ml, compiler/src/safety/safetyInterpreter.ml
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/791549131
=> Safety checker: fix lattice operations of the Init domain

CHANGELOG.md, compiler/src/alias.ml, compiler/tests/fail/stack_allocation/bug_54.jazz, compiler/tests/success/bug_54.jazz
Fixes #54
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/790822539
=> stack-allocation: fail early when merging slices

compiler/src/CLI_errors.ml, compiler/src/CLI_errors.mli, compiler/src/glob_options.ml, compiler/src/main_compiler.ml, compiler/src/utils.mli
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/792629480
=> CLI: improved errors

default.nix, opam, scripts/mathcomp-word.nix
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/793205073
=> opam: update mathcomp-word version constraint

.gitlab-ci.yml, CHANGELOG.md, compiler/.gitignore, compiler/.merlin, compiler/Makefile, compiler/_tags, compiler/default.nix, compiler/entry/jazz2tex.ml, compiler/opam, compiler/src/CLI_errors.ml, compiler/src/glob_options.ml, compiler/src/utils.ml, compiler/src/utils.mli, default.nix, opam
CI: https://gitlab.com/jasmin-lang/jasmin/-/pipelines/793711212
=> Make standalone the LATEX pretty-printer

CHANGELOG.md, compiler/safety/success/array_init.jazz, compiler/safety/success/bug_385.jazz, compiler/safety/success/bug_386.jazz, compiler/src/safety/safetyAbsExpr.ml
=> Safety checker: constant folding in linearization

compiler/src/subst.ml, proofs/compiler/compiler_proof.v, proofs/compiler/stack_alloc.v, proofs/compiler/stack_alloc_proof_2.v, proofs/lang/extraction.v, proofs/lang/warray_.v
Previous version was certainly quadratic, new version should be more linear.
=> reduce complexity of stack_alloc checker for global

proofs/compiler/stack_alloc.v, proofs/compiler/stack_alloc_proof_2.v
I dislike useless checks and I like procrastinating.
=> Remove useless check in stack alloc

AUTHORS, CHANGELOG.md
Cf. https://github.com/jasmin-lang/jasmin/pull/328
=> Fix AUTHORS and CHANGELOG.md

compiler/src/pretyping.ml, compiler/src/printCommon.ml, compiler/src/syntax.ml, compiler/src/tt_arm_m4.ml, compiler/src/tt_arm_m4.mli, proofs/compiler/arm_instr_decl.v, proofs/compiler/arm_instr_decl_lemmas.v
I wished I could expand the test suite, but printing of intrinsics is not correct yet: shifts are ignored.
=> Fixes to ARM parser & printer

CHANGELOG.md, proofs/compiler/arm_decl.v, proofs/compiler/arm_instr_decl.v, proofs/compiler/arm_lowering_proof.v, proofs/compiler/x86_instr_decl.v, proofs/compiler/x86_lowering.v, proofs/compiler/x86_lowering_proof.v, proofs/lang/sem_op_typed.v, proofs/lang/word.v
=> Fix source semantics of shifts

compiler/tests/success/arm-m4/bug_375.jazz, proofs/compiler/arm_lowering.v, proofs/compiler/arm_lowering_proof.v
=> ARM lowering: assignment of large (truncated) integers

CHANGELOG.md, compiler/src/regalloc.ml, compiler/tests/fail/register_allocation/x86-64/bug_421.jazz, compiler/tests/success/x86-64/cqo.jazz
=> Register allocation: check bank for forced registers

proofs/compiler/array_copy_proof.v, proofs/compiler/byteset.v, proofs/lang/memory_model.v, proofs/lang/type.v, proofs/lang/utils.v
Well-founded recursion is so beautiful!
=> ziota: implement without going through nat

compiler/src/lexer.mll
but that are interesting in themselves
=> Simplify the lexer a little bit

proofs/compiler/allocation_proof.v, proofs/compiler/constant_prop_proof.v, proofs/compiler/stack_alloc_proof.v, proofs/lang/psem.v, proofs/lang/type.v, proofs/lang/values.v
=> change the type constraint for Vundef, remove the use of compat_type

proofs/arch/arch_extra.v
=> Simplify a proof

CHANGELOG.md, eclib/JWord.ec, proofs/compiler/x86_instr_decl.v, proofs/lang/word.v
(based on top of #446 to prevent future merge conflicts)
=> x86: fix semantics of VPSHUFB and VPCMPGT

.gitlab-ci.yml, compiler/examples/gimli/arm-m4/gimli.jazz, compiler/examples/gimli/proofs/.gitignore, compiler/examples/gimli/proofs/Makefile, compiler/examples/gimli/proofs/ec.config, compiler/examples/gimli/proofs/gimli.ec, eclib/JModel_m4.ec, proofs/compiler/arm_instr_decl.v
This completes the EasyCrypt model for ARM-m4.
=> EasyCrypt: more precise model of ARM

proofs/compiler/remove_globals.v, proofs/lang/utils.v
Trivial cleaning to remove duplicate code.
=> Generalize find_map and use it in remove-globals

AUTHORS, CHANGELOG.md, compiler/src/CLI_errors.ml, compiler/src/utils.ml, compiler/src/utils.mli
I’m open to suggestions about the wording of the warning messages. Thanks.
=> Prepare version 2023.06

compiler/src/evaluator.ml, proofs/lang/sem_op_typed.v, proofs/lang/utils.v
It is not a type error
cc @x0000000001
=> Semantics: invalid division is an arithmetic error

.gitlab-ci.yml, default.nix, scripts/nixpkgs.nix
This will make possible to use Coq 8.17 & mathcomp 1.17
=> CI: update nix & nixpkgs

.gitlab-ci.yml, compiler/jasmin.opam, default.nix
Two questions to whoever may review this:
1. Is this way of selecting multiple files (`*.ec`) valid there?
2. Is is a right place for installing easycrypt libraries?
=> opam: install EasyCrypt libraries

compiler/src/coreIdent.ml, compiler/src/coreIdent.mli, compiler/src/prog.mli, compiler/src/regalloc.ml, compiler/src/ssa.ml
=> Regalloc: more precise error message

compiler/src/regalloc.ml, compiler/tests/fail/register_allocation/x86-64/bug_523.jazz
=> Regalloc: clearer error message

CHANGELOG.md, eclib/JWord.ec, proofs/compiler/x86_instr_decl.v
=> Fix semantics of IMUL* instructions

CHANGELOG.md, proofs/lang/word.v
=> ARM: fix semantics of SMLAL

compiler/jasmin.opam
Fix a typo introduced in #472.
=> opam: close variable interpolations in strings

CHANGELOG.md, compiler/src/pp_arm_m4.ml, eclib/JModel_m4.ec, proofs/compiler/arm_instr_decl.v
=> ARM: fix BIC & asm printer

compiler/src/conv.ml, proofs/compiler/dead_code.v, proofs/compiler/dead_code_proof.v
- Dead-code: use an option rather than a list
- Conv: use map instead of fold-right
=> Small improvements

proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v, proofs/compiler/inline_proof.v
=> Small refactoring of inlining

CHANGELOG.md, compiler/safety/success/bug_561.jazz, compiler/safety/success/div.jazz, compiler/safetylib/safetyInterpreter.ml, compiler/src/toEC.ml, proofs/compiler/x86_instr_decl.v, proofs/lang/wsize.v
=> Safety: do not crash on (I)DIV

proofs/compiler/linearization_proof.v, proofs/compiler/makeReferenceArguments_proof.v, proofs/compiler/x86_instr_decl.v, proofs/lang/expr.v, proofs/lang/sem_one_varmap.v, proofs/lang/sem_type.v, proofs/lang/utils.v
=> Small cleaning

compiler/src/iInfo.ml, proofs/compiler/array_init.v, proofs/compiler/array_init_proof.v, proofs/compiler/inline.v, proofs/lang/expr.v, proofs/lang/extraction.v
=> Add with_location to InstrInfo

CHANGELOG.md, compiler/src/pretyping.ml, compiler/tests/success/arm-m4/conditions.jazz, compiler/tests/success/x86-64/bug_599.jazz
=> Add != as flag combination

compiler/tests/success/slh/x86-64/spill_mmx.jazz, proofs/compiler/x86_extra.v, proofs/compiler/x86_params_proof.v
I didn't add anything to the CHANGELOG because we already have the SLH item, let me know if I should point this out.
=> Allow spilling MSFs to MMX

CHANGELOG.md, compiler/tests/success/common/bug_607.jazz, proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v
=> Remove dead functions after loop unrolling

compiler/src/regalloc.ml
That `assert false` is reachable…
Fixes #601.
=> Regalloc: fix assertion failure

compiler/src/printer.ml, proofs/compiler/compiler_util.v, proofs/compiler/linearization.v
=> Linearization: improve error message

compiler/src/sct_checker_forward.ml, compiler/tests/sct-checker/accept.expected, compiler/tests/sct-checker/sct_errors.expected, compiler/tests/sct-checker/success/for_loop.jazz
This error made the checker reject the test cases I added. The fix triggered the error message I changed which was rather confusing in the original phrasing.
=> SCT checker: Fix inference of for loops

CHANGELOG.md, compiler/tests/success/x86-64/xchg.jazz, eclib/JModel_common.ec, eclib/JModel_x86.ec, proofs/compiler/x86_instr_decl.v
With some help :-), I was able to create this PR.
I would like to be possible to exchange two register pointers as well.
=> add x86_64 xchg instruction.

proofs/compiler/arm_params_common.v, proofs/compiler/arm_params_common_proof.v, proofs/compiler/arm_params_proof.v, proofs/lang/linear_facts.v
Unify the smart immediate operations, and use `sem_fopn_args` more.
=> Share some definitions in arm_params_common

CHANGELOG.md, compiler/src/glob_options.ml, compiler/src/insert_copy_and_fix_length.ml, compiler/src/pretyping.ml, compiler/src/typing.mli, compiler/tests/success/common/spill.jazz, proofs/_CoqProject, proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v, proofs/compiler/inline_proof.v, proofs/compiler/lower_spill.v, proofs/compiler/lower_spill_proof.v, proofs/lang/pseudo_operator.v, proofs/lang/sopn.v
This is mostly to simplify the life of users.
Maybe it can be useful if we want to add spillable variables.
=> Add spill/unspill primitives

proofs/_CoqProject, proofs/compiler/riscv.v, proofs/compiler/riscv_decl.v, proofs/compiler/riscv_instr_decl.v, proofs/lang/sopn.v
=> Provides RISCV initial architecture description and first instructions (ADD / ADDI).

CHANGELOG.md, compiler/src/stackAlloc.ml, compiler/tests/success/arm-m4/large_stack/push_pop_to_save.jazz, proofs/compiler/arch_params_proof.v, proofs/compiler/arm_decl.v, proofs/compiler/arm_extra.v, proofs/compiler/arm_params.v, proofs/compiler/arm_params_common_proof.v, proofs/compiler/arm_params_core.v, proofs/compiler/arm_params_core_proof.v, proofs/compiler/arm_params_proof.v, proofs/compiler/arm_stack_zeroization_proof.v, proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v, proofs/compiler/linearization.v, proofs/compiler/linearization_proof.v, proofs/compiler/merge_varmaps.v, proofs/compiler/merge_varmaps_proof.v, proofs/compiler/x86_params.v, proofs/compiler/x86_params_proof.v, proofs/lang/linear_facts.v, proofs/lang/one_varmap.v, proofs/lang/psem.v, proofs/lang/sem_one_varmap.v, proofs/lang/sem_one_varmap_facts.v
=> fix #709 : push-pop on export function for arm

proofs/compiler/compiler_proof.v, proofs/compiler/linearization_proof.v
On top of https://github.com/jasmin-lang/jasmin/pull/710 to avoid conflicts.
Removes a FIXME.
EDIT: now that https://github.com/jasmin-lang/jasmin/pull/710 is merged, this is ready
=> Cleanup a hypothesis of linear_exportcallP

CHANGELOG.md, compiler/src/pretyping.ml
=> Catch required files that do not exist

compiler/src/help.ml, compiler/src/pretyping.ml, proofs/compiler/riscv.v, proofs/compiler/riscv_decl.v, proofs/compiler/riscv_instr_decl.v, proofs/lang/sopn.v
WIP for LOAD and STORE.
Co-authored-by: Jean-Christophe Léchenet
<jean-christophe.lechenet@inria.fr>
=> Adds SUB AND MOV.

proofs/compiler/riscv_instr_decl.v
=> Add XOR and OR to compiler/riscv_instr_decl.v

.gitlab-ci.yml, CHANGELOG.md, compiler/.gitignore, compiler/Makefile, compiler/default.nix, compiler/dune, compiler/entry/commonCLI.ml, compiler/entry/commonCLI.mli, compiler/entry/jazz2tex.ml, compiler/entry/jazzcheck.ml, compiler/jasmin.opam, compiler/scripts/check-cct, compiler/src/CLI_errors.ml, compiler/src/glob_options.ml
Prerequisite to further refactoring & improvements of the (S)CT checker.
=> Make standalone the security (CT) checker

proofs/compiler/arm_lowering_proof.v, proofs/compiler/arm_params_proof.v, proofs/compiler/array_copy_proof.v, proofs/compiler/array_expansion_proof.v, proofs/compiler/linearization_proof.v, proofs/compiler/stack_alloc_proof.v, proofs/compiler/stack_alloc_proof_2.v, proofs/compiler/x86_lowering_proof.v, proofs/lang/expr_facts.v, proofs/lang/memory_example.v, proofs/lang/memory_model.v, proofs/lang/psem.v, proofs/lang/psem_defs.v, proofs/lang/psem_facts.v, proofs/lang/sem_type.v, proofs/lang/syscall_sem.v, proofs/lang/utils.v, proofs/lang/values.v, proofs/lang/waes.v, proofs/lang/warray_.v, proofs/lang/word.v
This removes the (spurious) dependency on the axiomatic description of real numbers.
=> Favor Lia over Psatz

compiler/src/ppasm.ml
=> asm print: fix

compiler/src/regalloc.ml, compiler/tests/fail/register_allocation/arm-m4/no_mmx.jazz, compiler/tests/fail/register_allocation/arm-m4/no_vector.jazz
Fixes https://github.com/jasmin-lang/jasmin/issues/693
=> Reg alloc: error message when a bank is empty

CHANGELOG.md, compiler/CCT/success/speculative/bug_660.jazz, compiler/config/tests.config, compiler/entry/jazzct.ml
=> jazzct: optionally compile before checking

scripts/nixpkgs.nix, scripts/opam-setup.sh
1. Use OCaml 4.14.2
2. Update nixpkgs to get why3 1.7.2
=> Minor updates for the CI

proofs/lang/gen_map.v
Backward compatible, unblocks https://github.com/coq/coq/pull/18449
=> do not use SSR have in extracted code

compiler/src/conv.ml, compiler/src/conv.mli, compiler/src/stackAlloc.ml, compiler/src/uint63.mli, compiler/src/uint63_31.ml, compiler/src/uint63_63.ml, proofs/compiler/compiler.v, proofs/compiler/compiler_proof.v, proofs/compiler/makeReferenceArguments.v, proofs/compiler/makeReferenceArguments_proof.v, proofs/lang/extraction.v, proofs/lang/ident.v
Prepares extraction to native strings
=> Drop HexadecimalString

compiler/src/pp_arm_m4.ml, compiler/tests/fail/arm-m4/bug_667.jazz
=> ARM: improve error message for invalid addressing modes

compiler/tests/sct-checker/fail/basic.jazz, compiler/tests/sct-checker/fail/corruption.jazz, compiler/tests/sct-checker/reject.expected
Small additions to the test-suite of the SCT checker.
=> SCT checker: negative tests

compiler/examples/gimli/arm-m4/gimli.jazz, compiler/examples/gimli/proofs/gimli.ec, compiler/examples/gimli/proofs/gimli_ct.ec, compiler/examples/gimli/proofs/gimliv.ec, compiler/examples/gimli/x86-64/gimli.jazz
Use “smart LI” on arm and array in export functions!
=> Gimli: improve by using recent features

AUTHORS, compiler/scripts/runtest
As part of my work I needed to add new tests and ended up refactoring the `compiler/scripts/rutest` python script.
I also modified a bit the output format to be quiter about tests that pass (only kept a status line at the bottom with current progress and last test run).
Example output:
```
scripts/runtest --jobs="2" config/tests.config --report=report.log safety CCT x86-64-ATT x86-64-Intel x86-64-print x86-64-nolea arm-m4 arm-m4-print x86-64-stack-zero-loop x86-64-stack-zero-unrolled arm-m4-stack-zero-loop arm-m4-stack-zero-unrolled
Failed test ./scripts/check-x86-64 -ATT tests/success/x86-64/aes.jazz
--------------- Stdout ---------------
--------------- Stderr ---------------
+ dirname ./scripts/check-x86-64
+ ./scripts/../jasminc -g -o jasminAkFKxD/jasmin.s -ATT …
```
=> Refactor runtest and improve output readability.

.gitlab-ci.yml, default.nix, proofs/_CoqProject
The first commit is unrelated but might not deserve its own PR.
=> Use Coq 8.19

proofs/lang/memory_model.v, proofs/lang/word.v
=> Remove unused Ltac wring

CHANGELOG.md, compiler/tests/success/x86-64/bug_681.jazz, proofs/compiler/allocation_proof.v, proofs/compiler/constant_prop_proof.v, proofs/compiler/propagate_inline_proof.v, proofs/compiler/stack_alloc.v, proofs/compiler/stack_alloc_proof.v, proofs/compiler/stack_alloc_proof_2.v, proofs/lang/psem.v, proofs/lang/values.v
=> stack alloc: truncation of stack variables

compiler/src/liveness.ml
During register-allocation (i.e., when performing “weak” liveness analysis), values that are used in the left-hand side of an assignment (assgn, opn, call, syscall, etc.) are considered live after the instruction.
Fixes #634
=> Regalloc: improve liveness analysis

compiler/scripts/runtest
=> Improve test for easycrypt extraction

compiler/src/sct_checker_forward.ml, compiler/tests/sct-checker/accept.expected, compiler/tests/sct-checker/success/bug_852.jazz
=> SCT-checker: more precise handling of stack variables

CHANGELOG.md, compiler/src/toEC.ml
=> toEC (leakage extraction): fix for loop bound swap

compiler/jasmin.opam, opam
Cf. https://github.com/ocaml/opam-repository/pull/26224
=> opam: lower bound on angstrom

proofs/lang/utils.v
Should enable to unpin jasmin in Coq CI: https://github.com/coq/coq/pull/19432
Should be backward compatible and can be merged as soon as confirmed by CI here.
=> Compile with Coq master

compiler/src/toCL.ml
Based on [https://github.com/jasmin-lang/jasmin/commit/5003e53c5129741b660688716768e464e731131a](https://github.com/jasmin-lang/jasmin/commit/5003e53c5129741b660688716768e464e731131a).
=> Allow accessing subb borrow value

CHANGELOG.md, compiler/src/insert_copy_and_fix_length.ml, compiler/tests/fail/x86-64/unaligned_slice_copy.jazz, compiler/tests/success/common/arraycopy.jazz, compiler/tests/success/common/bug_842.jazz, proofs/compiler/array_copy.v, proofs/compiler/array_copy_proof.v, proofs/compiler/compiler.v
=> Add support for slices in array #copy

CHANGELOG.md, compiler/src/sct_checker_forward.ml, compiler/tests/sct-checker/accept.expected, compiler/tests/sct-checker/fail/basic.jazz, compiler/tests/sct-checker/fail/movmsf.jazz, compiler/tests/sct-checker/reject.expected, compiler/tests/sct-checker/success/movmsf.jazz
=> Relax the SCT checker

compiler/src/pretyping.ml
The brand new `tt_assign` function should prove useful soon.
=> pretyping: factor tt_assign out of tt_instr

compiler/src/sct_checker_forward.ml, compiler/tests/sct-checker/accept.expected, compiler/tests/sct-checker/fail/conditional-expr.jazz, compiler/tests/sct-checker/reject.expected, compiler/tests/sct-checker/success/conditional-expr.jazz
=> Solve TODO for conditional expressions in the SCT checker

eclib/JWord.ec
The lemmas about signed numbers have been adapted from the ML-KEM verification by Manuel & co.
=> eclib: add to_uintK_small, to_sintK_small, to_sintD_small, and to_sintB_small

CHANGELOG.md, compiler/src/x86_arch_full.ml, compiler/tests/success/x86-64/bt.jazz, eclib/JModel_x86.ec, eclib/JWord.ec, proofs/compiler/x86_instr_decl.v
~This is missing EasyCrypt definitions.~
=> Add x86 instructions BTR/BTS

eclib/JModel_m4.ec, eclib/JWord.ec
And expose it as part of the WT theory
=> eclib: new notation |>>> for arithmetic right shift

compiler/entry/jasmin2tex.ml
This program
```
export
fn ble() {
() = #spill(0);
}
```
produced
```
jasmin2tex: internal error, uncaught exception:
Jasmin.Pretyping.TyError(_, _)
```
=> Catch exceptions in jasmin2tex

CHANGELOG.md, compiler/dune, compiler/safetylib/dune, compiler/src/dune, compiler/src/pretyping.ml, compiler/src/printer.ml, compiler/src/printer.mli, compiler/src/prog.ml, compiler/src/prog.mli, compiler/src/subst.ml, compiler/tests/exec/dune, compiler/tests/sct-checker/dune
=> Get rid of recursive types

compiler/examples/jazzline/curve25519/common/add4/add4.jazz, compiler/examples/jazzline/curve25519/common/sub4/sub4.jazz, compiler/examples/jazzline/curve25519/mulx/mul4/mul4_a24.jazz, compiler/examples/jazzline/curve25519/mulx/mul4/mul4_rsr.jazz, compiler/examples/jazzline/curve25519/mulx/mul4/reduce4.jazz, compiler/examples/jazzline/curve25519/mulx/reduce4/reduce4.jazz, compiler/examples/jazzline/curve25519/mulx/sqr4/reduce4.jazz, compiler/examples/jazzline/curve25519/mulx/sqr4/sqr4.jazz, compiler/examples/jazzline/curve25519/ref4/mul4/mul4_a24.jazz, compiler/examples/jazzline/curve25519/ref4/mul4/mul4_rss.jazz, compiler/examples/jazzline/curve25519/ref4/mul4/reduce4.jazz, compiler/examples/jazzline/curve25519/ref4/reduce4/reduce4.jazz, compiler/examples/jazzline/curve25519/ref4/sqr4/reduce4.jazz, compiler/examples/jazzline/curve25519/ref4/sqr4/sqr4.jazz, compiler/src/toCL.ml
Depends on https://github.com/jasmin-lang/jasmin/pull/944,  https://github.com/jasmin-lang/jasmin/pull/945 and https://github.com/jasmin-lang/jasmin/pull/946.
This merge request adds jazzline examples that do not require anymore changes to the toCL file.
=> Cryptoline curve25519 examples

compiler/src/toEC.ml
Follow-up to #971 
Improve the handling of leakage aux variables, and also removes the `pop_aux/reset_aux` functions (these seem likely to lead to bugs if forgotten), and replace them with a new function that creates a new env when entering an operation that may use new aux vars (this assumes aux var usage to be properly nested, which currently holds, and seems reasonable).
=> Ec extraction: cleanup leak aux variables

.gitlab-ci.yml, scripts/nixpkgs.nix
This fixes the `coq-master` job.
=> CI: update nixpkgs

CHANGELOG.md, compiler/entry/jasmin2ec.ml, compiler/examples/gimli/proofs/gimliv.ec, compiler/src/toEC.ml, compiler/src/toEC.mli, compiler/tests/success/x86-64/array_cast.jazz, eclib/JArray.ec, eclib/JByte_array.ec, eclib/JWord.ec
=> use byte array in extraction

CHANGELOG.md, compiler/src/x86_arch_full.ml, compiler/tests/success/x86-64/vector.jazz, eclib/JModel_x86.ec, eclib/JWord.ec, proofs/compiler/x86_instr_decl.v, proofs/lang/word.v
=> x86: add support for VPABS (AVX) instructions

compiler/src/sct_checker_forward.ml
There have been reports of performance issues with the SCT checker.
This change is meant to improve run-time performance by dropping internal information about dead variables.
The single data point I have supporting this change is that checking a particular implementation of ML-KEM for DOIT takes 30mn before this change and 5s after.
=> SCT checker: kill dead vars

CHANGELOG.md, compiler/src/x86_arch_full.ml, compiler/tests/success/x86-64/vpcmp.jazz, eclib/JModel_x86.ec, eclib/JWord.ec, proofs/compiler/x86_instr_decl.v
=> x86: add support for VPSIGN (AVX) instructions

proofs/compiler/load_constants_in_cond.v, proofs/compiler/load_constants_in_cond_proof.v, proofs/compiler/riscv.v, proofs/compiler/riscv_lower_addressing.v, proofs/compiler/riscv_stack_zeroization_proof.v, proofs/compiler/x86_instr_decl.v, proofs/lang/utils.v
=> Minor fixes for recent Coq / math-comp

compiler/src/pretyping.ml
Make the `InvalidType` error more specific then remove the `typattern` data type and associated functions (`pp_typat` and `check_ty`).
=> Pretyping: remove dead code

.gitlab-ci.yml, Makefile.compiler
Useful for packages & distribution
=> Add Makefile to jasmin-compiler repository

default.nix, opam, proofs/3rdparty/xseq.v, proofs/compiler/stack_alloc_proof_2.v, proofs/ssrmisc/oseq.v
Adapt to https://github.com/math-comp/math-comp/pull/1343
Should fix Coq CI
=> Adapt to https://github.com/math-comp/math-comp/pull/1343

compiler/src/latex_printer.ml
Closes #1060. I believe I'm handling the `GEstring` case correctly, but I would like some confirmation.
=> Improve printing of problematic characters in jasmin2tex

CHANGELOG.md
This should incorporate all changes proposed in #1051 (please complain if it is not the case).
Closes #1051.
=> Update CHANGELOG after release 2024.07.3

CHANGELOG.md, compiler/entry/commonCLI.ml, compiler/entry/commonCLI.mli, compiler/entry/jasmin2ec.ml, compiler/entry/jasmin2tex.ml, compiler/entry/jasmin_ct.ml, compiler/src/compile.ml, compiler/src/compile.mli, compiler/src/glob_options.ml, compiler/src/main_compiler.ml
This reverts #1061 and revives #1042.
=> Add support for the -I parameter to jasmin2ec, jasmin-ct and jasmin2tex

compiler/examples/extraction-unit-tests/proofs.ec, eclib/JByte_array.ec, eclib/JMemory.ec
These calls to SMT solvers have been failing in CI recently.
=> Simplify proofs for SMTs

CHANGELOG.md, compiler/src/x86_arch_full.ml, compiler/tests/success/x86-64/movemask.jazz, eclib/JModel_x86.ec, proofs/compiler/x86_instr_decl.v, proofs/lang/word.v
It covers VMOVMSKPS, VMOVMSKPD, and VPMOVMSKB.
=> x86: add MOVEMASK instrinsics

CHANGELOG.md, eclib/JModel_m4.ec, proofs/compiler/arm_instr_decl.v
Bug found by randomized testing.
=> ARM: fix semantics of the carry flag for LSR

CHANGELOG.md, compiler/examples/extraction-unit-tests/.gitignore, compiler/examples/extraction-unit-tests/Makefile, compiler/examples/extraction-unit-tests/proofs.ec, compiler/examples/extraction-unit-tests/sdiv.jazz, eclib/JUtils.ec, eclib/JWord.ec
Extracted from https://github.com/jasmin-lang/jasmin/pull/1071 and added a non-regression test case.
=> Fix EC extraction of signed division

opam, proofs/compiler/lea_proof.v, proofs/lang/gen_map.v, proofs/lang/low_memory.v, proofs/lang/memory_example.v, proofs/lang/waes.v
Adapt to https://github.com/math-comp/math-comp/pull/1354
=> Adapt to https://github.com/math-comp/math-comp/pull/1354

scripts/easycrypt.nix
https://github.com/EasyCrypt/easycrypt/releases/tag/r2025.03
=> CI: use EasyCrypt 2025.03

CHANGELOG.md, compiler/src/x86_arch_full.ml, compiler/tests/success/x86-64/sha256.jazz, eclib/JModel_x86.ec, eclib/SHA.ec, proofs/_CoqProject, proofs/compiler/x86_instr_decl.v, proofs/lang/sha256.v
=> x86: add SHA256MSG1, SHA256MSG2 & SHA256RNDS2

compiler/src/liveness.ml, compiler/src/prog.ml, compiler/src/prog.mli
Little PR to factorise computation of the set of returned variables for a given function
=> Factorisation

CHANGELOG.md, compiler/src/pretyping.ml, compiler/tests/fail/slh/x86-64/intrinsic_kills_msf.jazz, compiler/tests/success/common/test_keep.jazz, compiler/tests/success/x86-64/bug_1138.jazz, compiler/tests/success/x86-64/bug_1139.jazz
=> Mark flag combinations as inline instructions & introduce #keep to control DCE

compiler/src/compile.ml, compiler/src/regalloc.ml, compiler/src/regalloc.mli
Does anyone remember the use for exposing these functions from `Ssa` as part of the `Regalloc` module?
=> Remove indirection

compiler/src/liveness.ml, compiler/src/prog.ml, compiler/src/prog.mli, compiler/src/varalloc.ml
This traverses a statement and apply a call-back function to every instruction
=> Add utility function Prog.iter_instr

compiler/safetylib/safetyConfig.ml
type `kind` of safetyConfig.ml file (in safetylib package) is not used. This PR removes it. It also make a little formatting on the file (by removing whitespaces and aligning tabs).
=> removing type `kind` from safetyConfig

proofs/compiler/makeReferenceArguments.v, proofs/compiler/makeReferenceArguments_proof.v, proofs/lang/expr_facts.v
This PR introduce the proof of makeReferenceArguments using itree semantics.
It was necessary to modified a little the code of makeReferenceArguments (adding some extra tests),
without them I am not able to do the proof using itree semantics.
=> IT proof of makeReferenceArguments

CHANGELOG.md, compiler/src/insert_copy_and_fix_length.ml, compiler/src/typing.ml, compiler/src/typing.mli
=> Typing: check length non-negative

proofs/compiler/array_copy_proof.v, proofs/compiler/dead_code.v, proofs/compiler/dead_code_proof.v, proofs/lang/psem.v
Proof of dead_code using ITree semantics.
=> IT proof of dead_code

proofs/compiler/allocation_proof.v, proofs/compiler/constant_prop_proof.v, proofs/compiler/lower_spill_proof.v, proofs/compiler/propagate_inline_proof.v, proofs/lang/psem.v, proofs/lang/relational_logic.v
The first commit generalises some lemmas/definitions in relational_logic, the second use that to do the proof of propagate_inline.
=> IT proof of propagate_inline

proofs/compiler/remove_globals_proof.v, proofs/lang/relational_logic.v
IT proof of remove_global.
Add transitivity lemma for wiequiv_f that will be useful for the composition of all the compilation pass.
=> IT proof of remove_global

proofs/compiler/array_expansion_proof.v, proofs/compiler/compiler_util.v, proofs/compiler/slh_lowering.v, proofs/compiler/slh_lowering_proof.v, proofs/compiler/stack_alloc_proof_1.v, proofs/lang/expr_facts.v, proofs/lang/it_sems_core.v, proofs/lang/psem_core.v, proofs/lang/relational_logic.v, proofs/lang/slh_ops.v, proofs/lang/sopn.v, proofs/lang/utils.v
I also added `o2rP` to `t_xrbindP` and moved `is_reflect` to utils.
=> Move slh lowering to ITrees

proofs/compiler/allocation_proof.v, proofs/compiler/wint_word.v, proofs/compiler/wint_word_proof.v
Proof of wint_word based on itree semantics.
=> IT proof of wint_word

compiler/entry/commonCLI.ml, compiler/examples/extraction-unit-tests/.gitignore, compiler/src/ssa.mli
Côme, can you please remind us the purpose of the RISC-V test case? (ping @clebreto)
=> Minor cleaning

CHANGELOG.md
Thanks Jean-Christophe for the nice polishing.
=> Update CHANGELOG after release 2025.06.0

compiler/tests/fail/stack_allocation/x86-64/out_of_bounds_read.jazz, compiler/tests/fail/stack_allocation/x86-64/out_of_bounds_read_neg.jazz, compiler/tests/fail/stack_allocation/x86-64/out_of_bounds_read_partial.jazz, compiler/tests/fail/stack_allocation/x86-64/out_of_bounds_write.jazz, compiler/tests/fail/stack_allocation/x86-64/out_of_bounds_write_neg.jazz, proofs/compiler/stack_alloc.v, proofs/compiler/stack_alloc_proof_1.v
=> Reject trivially out-of-bounds array accesses

AUTHORS, proofs/itrees/rec_facts.v
I forgot to do it in the first commit for inlining, we should correct that
=> add acknowledgment

CHANGELOG.md, compiler/src/regalloc.ml, compiler/tests/fail/register_allocation/x86-64/bug_426.jazz, compiler/tests/fail/register_allocation/x86-64/bug_426_bis.jazz
=> Regalloc: dead function arguments do conflict with each other

docs/source/conf.py, docs/source/index.md, docs/source/misc/installation_guide.md
Explain what to install and how.
Fixes #1259
=> Docs: installation guide

scripts/easycrypt.nix
https://github.com/EasyCrypt/easycrypt/releases/tag/r2025.10
=> CI: use EasyCrypt 2025.10
